[14.0][MIG] partner_contact_address_default: Migration to 14.0
OCA/partner-contact pull request #1066
Opened 2021-02-18 14:48 UTC by Zar21

Standard migration Odoo 14.0

2021-02-19 16:17 UTC, HaraldPanten approved these changes
Functional review

2021-09-25 22:55 UTC, vanderperre approved these changes

2021-09-25 23:23 UTC, pedrobaeza commented
/ocabot merge nobump

2021-09-25 23:42 UTC, vanderperre requested changes
It will be wonderful if the domain proposed is not only limited by myself (address) or by my childs but also of all contacts of the delivery/invoice type.  A search read would be able to place/sort my favourites contacts (me and my childs) and after the other ...  Also i have see a bug when you create/update a partner: you can select myself as delivery or invoice default but if you change the company type of the partner, this selection become empty ...

2021-09-25 23:52 UTC, merged