14 dr partner stage
OCA/partner-contact pull request #1192
Opened 2021-12-07 18:49 UTC by dreispt

- [14.0][ADD] partner_identification_notification.
- Add module to manage GLN partner identification number
- OCA Transbot updated translations from Transifex
- [MIG] Partner Identification Gln v10
- [MIG] partner_identification_gln: Migration to 12.0
- [13.0][MIG] - migration partner_identification_gln
- [IMP] partner_identification_gln: black, isort, prettier
- partner_identification_gln: migrate to v14
- [FIX] base_location: address field sync city_id TT33047
- [UPD] Update partner_identification_gln.pot
- [UPD] addons table in README.md
- [UPD] README.rst
- [ADD] setup.py
- Translated using Weblate (Portuguese (Portugal))
- base_location 14.0.1.2.3
- [UPD] addons table in README.md
- [UPD] Update partner_identification_notification.pot
- [UPD] addons table in README.md
- [UPD] README.rst
- [ADD] setup.py
- [ADD] partner_stage: add lifecycle stages to Contacts

2021-12-07 20:28 UTC, patrickrwilson requested changes
Tested and works well but needs some changes and travis needs fixed.

2021-12-07 20:28 UTC, patrickrwilson commented on partner_stage/models/res_partner_stage.py
> +    _description = "Product Stage"
Change Product to Partner.

2021-12-07 20:28 UTC, patrickrwilson commented on partner_stage/tests/test_partner_stage.py
> +class TestProductState(SavepointCase):
Change 'Product' to 'Partner' and fix error that shows in travis.

2021-12-07 20:28 UTC, patrickrwilson commented on partner_stage/views/res_partner_stage_views.xml
> +            <tree string="product.state">
Change from 'product' to 'partner'

2021-12-07 20:28 UTC, patrickrwilson commented on partner_stage/views/res_partner_stage_views.xml
> +    <record model="ir.ui.menu" id="menu_product_state">
Change from 'product' to 'partner'

2021-12-08 09:03 UTC, dreispt commented
@patrickrwilson Fixed!

2021-12-09 09:58 UTC, dreispt commented
Added "state", plus corresponding migration scrips from previous version.

2022-02-02 11:47 UTC, vongoethe approved these changes
Works great!

2022-02-17 23:05 UTC, rafaelbn approved these changes

2022-02-17 23:06 UTC, rafaelbn commented
/ocabot merge nobump

2022-02-17 23:56 UTC, merged