[13.0][IMP] partner_company_group: Add advises when company_group pricelist is different than member pricelists
OCA/partner-contact pull request #1252
Opened 2022-04-04 07:41 UTC by CarlosRoca13

cc @Tecnativa TT35300

please @carlosdauden @sergio-teruel review this

2022-04-04 07:59 UTC, carlosdauden approved these changes

2022-04-04 07:59 UTC, carlosdauden commented on partner_company_group/models/res_partner.py
> +        elif (
You could extract the common code to a new method to not repeat the same code ([DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)).
Or in this case call direcly to _onchange_company_group_id
```suggestion
        res = self._onchange_company_group_id()
        if not res:
```

2022-04-04 08:24 UTC, CarlosRoca13 commented
Changed!

2022-04-04 21:02 UTC, sergio-teruel requested changes
@CarlosRoca13 please add some test to coverage this behavior

2022-04-07 10:03 UTC, sergio-teruel commented
ping @CarlosRoca13

2022-04-07 11:28 UTC, CarlosRoca13 commented
Sorry for the delay, added

2022-04-07 13:38 UTC, sergio-teruel approved these changes

2022-04-08 08:11 UTC, rousseldenis reviewed
LGTM

2022-04-08 08:11 UTC, rousseldenis approved these changes

2022-04-08 12:13 UTC, pedrobaeza commented
/ocabot merge minor

2022-04-08 12:50 UTC, merged