[ADD] search method for partner age
OCA/partner-contact pull request #1287
Opened 2022-06-07 09:13 UTC by victor-champonnois

This PR adds a `_search_age` method for partner's `age` computed field. Tests are also added.

2022-06-08 13:09 UTC, robinkeunen approved these changes

2022-06-24 08:07 UTC, carmenbianca requested changes

2022-06-24 08:07 UTC, carmenbianca commented on partner_contact_birthdate/models/res_partner.py
> +        self.env.cr.execute(query, (value,))
I don't think `in` and `not in` are valid SQL. They should be removed from the list of operators.

2022-06-24 09:04 UTC, victor-champonnois commented on partner_contact_birthdate/models/res_partner.py
> +        self.env.cr.execute(query, (value,))
It exists in [PostgreSQL's doc ](https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-IN), why do you think it's not valid?

2022-06-24 13:32 UTC, carmenbianca commented on partner_contact_birthdate/models/res_partner.py
> +        self.env.cr.execute(query, (value,))
Huh, you may be right. Can you maybe add a test for them?

2022-06-24 14:34 UTC, carmenbianca commented on partner_contact_birthdate/models/res_partner.py
> +        self.env.cr.execute(query, (value,))
On second inspection: I think they don't work. The operators require a subquery.

2022-06-24 14:38 UTC, victor-champonnois commented on partner_contact_birthdate/models/res_partner.py
> +        self.env.cr.execute(query, (value,))
OK let's just remove them.

2022-06-24 14:53 UTC, carmenbianca approved these changes
LGTM! :tada:

2022-10-01 14:28 UTC, dreispt commented
/ocabot merge minor

2022-10-01 14:55 UTC, merged