[14.0][ADD] partner_category_security: New addon.
OCA/partner-contact pull request #1328
Opened 2022-08-25 10:02 UTC by victoralmau

New addon.

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT38576

2022-08-25 12:46 UTC, CarlosRoca13 approved these changes
Code review :+1:

2022-08-25 18:13 UTC, pedrobaeza requested changes

2022-08-25 18:13 UTC, pedrobaeza commented on partner_category_security/README.rst
> +This module adds permissions to manage contact labels.
```suggestion
This module adds a specific security group to manage contact tags (categories).
```

2022-08-25 18:13 UTC, pedrobaeza commented on partner_category_security/README.rst
> +#. *Contact Tags > Publisher* permission allows you to modify contact tags.
```suggestion
#. *Contact Tags > Publisher* permission allows you to modify the tags assigned to contacts.
```

2022-08-25 18:13 UTC, pedrobaeza commented on partner_category_security/README.rst
> +#. *Contact Tags > Manager* permission also allows you to create and delete contact tag records.
```suggestion
#. *Contact Tags > Manager* permission also allows you to manage such tag (create, modify or remove them).
```

2022-08-25 18:13 UTC, pedrobaeza commented on partner_category_security/README.rst
> +#. *Contacts > Configuration > Contact Tags* menu will only be visible if you have one of these permissions.
It should be only available if the latest one is granted.

2022-08-25 18:13 UTC, pedrobaeza commented on partner_category_security/README.rst
> +#. *Extra Rights / Contact Creation* permission now only allows reading contact tag records.
I think all internal users should have read permission.

2022-08-26 06:18 UTC, victoralmau commented
Changes done

2022-08-26 07:04 UTC, pedrobaeza commented
I have tried in runbot, and I'm able to change tags in the partner with no permission assigned.

2022-08-26 07:08 UTC, victoralmau commented
> I have tried in runboat, and I'm able to change tags in the partner with no permission assigned.

Ok, I guess you are testing with the demo user. 

You will need to add a glue module with `crm` (`partner_category_security_crm`) because this rule https://github.com/odoo/odoo/blob/14.0/addons/crm/security/ir.model.access.csv#L7 gives permissions to do so and you will need to overwrite it.

Do you think I should add that new addon in this PR?

2022-08-26 07:12 UTC, pedrobaeza commented
I don't think it's something of the CRM glue module. It's simply that the field is not readonly for that group. You have to modify the view and add 2 times the field: one only readonly and available for the basic internal user, and other not readonly if you have the other permission.

2022-08-26 07:31 UTC, victoralmau commented
> I don't think it's something of the CRM glue module. It's simply that the field is not readonly for that group. You have to modify the view and add 2 times the field: one only readonly and available for the basic internal user, and other not readonly if you have the other permission.

Ok, you're right, I hadn't thought of that approach. It is already added.

2022-08-26 07:49 UTC, pedrobaeza commented on partner_category_security/views/res_partner_view.xml
> +                    readonly="1"
Don't break any automatism on onchanges.

```suggestion
                    readonly="1"
                    force_save="1"
```

2022-08-26 08:20 UTC, victoralmau commented
Changes done

2022-08-26 09:21 UTC, pedrobaeza approved these changes

2022-08-26 09:21 UTC, pedrobaeza commented
/ocabot merge nobump

Please proceed with the CRM extension

2022-08-26 09:34 UTC, merged