[15.0][ADD] partner_name_hide_parent : New Module
OCA/partner-contact pull request #1338
Opened 2022-09-14 05:42 UTC by AungKoKoLin1997

This module does the following:

- Adds the ability to hide parent's name from the presentation of the partners' names according to the settings of the partners.
- The function provided by this module is needed when you have to set up a child partner (e.g. a branch office of a company) as an 'individual' due to how Odoo recognizes the commercial partner (i.e. if a child partner is a 'company', the partner becomes the commercial partner itself), and you do not want to show the parent's name in QWeb report or website where the partner is referenced (if the child partner is an individual, Odoo by default shows the parent's name preceding the child's name)

2022-09-15 03:31 UTC, yostashiro requested changes

2022-09-15 03:31 UTC, yostashiro commented on partner_name_hide_parent/models/res_partner.py
> +        # Following two lines are inserted. (QRTL)
```suggestion
    def _get_contact_name(self, partner, name):
```

2022-09-15 03:31 UTC, yostashiro commented on partner_name_hide_parent/readme/DESCRIPTION.rst
> +  The function provided by this module is needed when you have to set up a child partner (e.g. a branch office of a company) as an 'individual' due to how Odoo recognizes the commercial partner (i.e.
```suggestion

The function provided by this module is needed when you have to set up a child partner
(e.g. a branch office of a company) as an 'individual' due to how Odoo recognizes the
commercial partner (i.e. if a child partner is a 'company', the partner becomes the
commercial partner itself), and you do not want to show the parent's name in QWeb report
or website where the partner is referenced (if the child partner is an individual, Odoo
by default shows the parent's name preceding the child's name).
```
Just to adjust the formatting.

2022-09-15 03:31 UTC, yostashiro commented on partner_name_hide_parent/__manifest__.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
```suggestion
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
```
Can we switch to AGPL for this one.

2022-09-15 04:07 UTC, yostashiro requested changes

2022-09-15 04:07 UTC, yostashiro commented on partner_name_hide_parent/readme/DESCRIPTION.rst
> +  by default shows the parent's name preceding the child's name).
```suggestion

The function provided by this module is needed when you have to set up a child partner
(e.g. a branch office of a company) as an 'individual' due to how Odoo recognizes the
commercial partner (i.e. if a child partner is a 'company', the partner becomes the
commercial partner itself), and you do not want to show the parent's name in QWeb report
or website where the partner is referenced (if the child partner is an individual, Odoo
by default shows the parent's name preceding the child's name).
```
This part explains the background and not the function, therefore it is not appropriate to be made part of what the module does.

2022-09-15 04:16 UTC, yostashiro approved these changes
👍

2023-01-17 04:42 UTC, rinaldifirdaus approved these changes
Functional test in local environment and working well.

2023-03-31 16:58 UTC, dreispt commented
/ocabot merge nobump

2023-03-31 17:07 UTC, merged