[IMP][14.0] partner_email_check: updated module name
OCA/partner-contact pull request #1352
Opened 2022-10-03 11:30 UTC by AshishHirapara

Updated name and description of the module
name update: from - Email Format Checker
to
Partner Email Format and Duplicate Checker

2022-10-03 12:45 UTC, francesco-ooops approved these changes
Improves searchability of module function

@rousseldenis merge?

2022-10-18 13:19 UTC, francesco-ooops commented
@rafaelbn can you take a look? thanks!

2022-10-18 13:29 UTC, rafaelbn commented
I don't use this module maybe @janverb or @Abranes could review it 😄

2022-10-18 13:43 UTC, francesco-ooops commented
@rafaelbn it's no big change, it's just a clarification of what this module does, to make it easier to find :)

2022-10-18 15:16 UTC, Abranes commented
@rafaelbn @francesco-ooops I think that this modification of the name shouldn't be made because making the email unique is something optional in the module and I don't see it correct to indicate it in the name itself, it's enough to indicate it in the readme.

2022-10-18 15:22 UTC, francesco-ooops commented
@Abranes yes, but at the same time also checking the validity of the email is optional (all features of this module are optional and managed in config). 

I asked for the name to be expanded just because I was looking for a module to avoid duplicate email and didn't find with keyword "duplicate" which is a quite useful feature of this module. 

So I don't think having more information in the module title hurts anyone, it's good for searching, then there is always readme :)

2022-10-18 15:29 UTC, Abranes commented
@francesco-ooops maybe we can add this information in the module summary (the summary is shown in the repository's available addons table)

2022-10-18 15:34 UTC, francesco-ooops requested changes

2022-10-18 15:34 UTC, francesco-ooops commented on partner_email_check/__manifest__.py
> +    "name": "Partner Email Format and Duplicate Checker",
@AshishHirapara remove

2022-10-18 15:34 UTC, francesco-ooops commented on partner_email_check/__manifest__.py
>      "summary": "Validate email address field",
"summary": "Normalize, validate and/or prevent duplicates in email address field,",

2023-03-26 12:32 UTC, closed without merging