16.0 add partner subject to vat
OCA/partner-contact pull request #1461
Opened 2023-02-03 09:59 UTC by victor-champonnois

2023-04-26 14:20 UTC, robinkeunen approved these changes

2023-04-26 14:21 UTC, carmenbianca requested changes
Small suggestions, otherwise LGTM.

I leave it to the PSC to determine whether this module belongs in `partner-contact`

2023-04-26 14:21 UTC, carmenbianca commented on partner_subject_to_vat/models/res_partner.py
> +    subject_to_vat = fields.Boolean(string="Subject to VAT")
```suggestion
    is_subject_to_vat = fields.Boolean(string="Is Subject to VAT")
```

2023-04-26 14:21 UTC, carmenbianca commented on partner_subject_to_vat/__manifest__.py
> +    "application": False,
not needed

2023-04-26 14:21 UTC, carmenbianca commented on partner_subject_to_vat/__manifest__.py
> +    "qweb": [],
keys with empty values can be deleted

2023-04-26 14:29 UTC, victor-champonnois commented on partner_subject_to_vat/__manifest__.py
> +    "qweb": [],
fixed

2023-04-26 14:29 UTC, victor-champonnois commented on partner_subject_to_vat/__manifest__.py
> +    "application": False,
fixed

2023-04-26 14:30 UTC, victor-champonnois commented on partner_subject_to_vat/models/res_partner.py
> +    subject_to_vat = fields.Boolean(string="Subject to VAT")
fixed

2023-04-26 14:32 UTC, carmenbianca approved these changes

2023-05-03 13:23 UTC, victor-champonnois commented
@gurneyalex @simahawk @bguillot Can this be merged ?

2023-07-12 12:27 UTC, carmenbianca commented
@OCA/crm-sales-marketing-maintainers Kindly pinging for a merge/review :)

2023-11-06 10:34 UTC, NL66278 approved these changes
:+1:  LGTM

2023-11-17 23:09 UTC, dreispt commented
/ocabot merge nobump

2023-11-17 23:31 UTC, merged