[16.0][MIG] sale_partner_company_group
OCA/partner-contact pull request #1520
Opened 2023-05-10 15:32 UTC by Highcooley

2023-07-11 13:08 UTC, stefan-tecnativa approved these changes
Tested. LGTM 

TT44356

2023-07-27 10:11 UTC, km-landoo commented
@Highcooley could you reload the runbot pls?

2023-08-08 05:10 UTC, stefan-tecnativa commented
You should squash your last commit into the migration one. Can you do it please?

2023-08-08 05:36 UTC, Highcooley commented
@stefan-tecnativa Done

2023-08-08 05:45 UTC, pedrobaeza commented
/ocabot migration sale_partner_company_group

2023-08-08 05:49 UTC, pedrobaeza requested changes
I still see 2 migration commits, and you can squash commits this way:

![Selección_034](https://github.com/OCA/partner-contact/assets/7165771/8982ee68-026c-4c55-854b-f0045715eeaa)

2023-08-08 05:49 UTC, pedrobaeza commented on sale_partner_company_group/__manifest__.py
> +    "version": "16.0.0.1.0",
Incorrect version: It should be `16.0.1.0.0`

2023-08-08 05:49 UTC, pedrobaeza commented on sale_partner_company_group/i18n/partner_company_group.pot
This file should go out

2023-08-08 05:58 UTC, Highcooley commented
@pedrobaeza partner_company_group.pot removed, however the manifest is already on 16.0.1.0.0

2023-08-08 05:59 UTC, pedrobaeza commented
OK, the change was done in other commit. What about the squashing of the other commits?

2023-08-08 06:42 UTC, Highcooley commented
@pedrobaeza here we go

2023-08-08 06:43 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2023-08-08 06:51 UTC, merged