[14.0][ADD] partner_tag_smart_assignation
OCA/partner-contact pull request #1532
Opened 2023-06-01 12:33 UTC by ecino

New module for tagging partners automatically based on search filters or SQL queries.

2023-10-16 06:50 UTC, ecino commented
Anybody willing to review this new module? I think it brings a nice feature addition.

2023-11-06 15:42 UTC, NL66278 approved these changes
:+1: LGTM

2023-11-06 15:43 UTC, NL66278 commented
@ecino please rebase and force push again to rerun tests

2024-03-25 11:31 UTC, NL66278 commented on partner_tag_smart_assignation/cron/update_cron.xml
> +<odoo>
On cron data added this way it is best to use the noupdate flag, so changed to the cronfiguration (runtime, active or not, etc.) are not undone by an update.

2024-03-25 11:45 UTC, NL66278 commented on partner_tag_smart_assignation/tests/test_smart_tagger.py
> +        expired_tag.update({"valid_until": yesterday})
You must use `write` here and then call the _check_validity_dates method manually, as the scheduler will not run immediately. `update`  only updates the in memory record.

2024-03-25 11:46 UTC, NL66278 commented on partner_tag_smart_assignation/tests/test_smart_tagger.py
> +        # Reload the tags from the database
This is not needed. Actually updating the database through write, will update the database (and the cache). invalidate_cache can be useful after changing stuff through SQL.

2024-03-25 11:51 UTC, NL66278 commented on partner_tag_smart_assignation/models/hr_department.py
> +# Copyright (C) 2019 Compassion CH (http://www.compassion.ch)
Your module could be useful for many organisations that do not have `hr`  installed. So better not to have `hr`  as a dependency. Put the `hr` modification in a separate module (partner_tag_smart_assignation_hr), that depends on both this module and hr.

2024-03-25 11:52 UTC, NL66278 requested changes
:+1: Thanks for your contribution. Please take up requested changed so we can approve this.

2024-04-28 12:32 UTC, closed without merging