[17.0][MIG] base_partner_sequence: Migration to 17.0
OCA/partner-contact pull request #1683
Opened 2024-03-01 21:56 UTC by FSchiepers

2024-03-02 10:52 UTC, pedrobaeza commented
/ocabot migration base_partner_sequence

2024-04-04 03:52 UTC, nguyenminhchien requested changes

2024-04-04 03:52 UTC, nguyenminhchien commented on base_partner_sequence/views/partner_view.xml
> +                >{'readonly': [['is_company', '=', False], ['parent_id', '!=', False]]}</attribute>
Attr options does not work from my side. my suggestion:
`<attribute name="readonly">not is_company and parent_id</attribute>`

2024-04-04 03:52 UTC, nguyenminhchien commented on base_partner_sequence/models/partner.py
> +            super().write(partner_vals)
it must be `super(ResPartner, partner).write(partner_vals)` because this line is in the loop `for partner in self:`

2024-04-04 03:52 UTC, nguyenminhchien commented on base_partner_sequence/tests/test_base_partner_sequence.py
> +            partner.write({"ref": False})
Don't make these changes, my suggestion above (in `def write(self, vals)` of `partner.py`) solves your issue.

2024-04-04 03:52 UTC, nguyenminhchien commented on base_partner_sequence/tests/test_base_partner_sequence.py
> +            partner.write({})
Don't make these changes, my suggestion above (in `def write(self, vals)` of `partner.py`) solves your issue.

2024-04-08 09:46 UTC, FSchiepers commented
New Review required after I changed the code according to [nguyenminhchien](https://github.com/nguyenminhchien)'s suggestions

2024-04-08 11:03 UTC, nguyenminhchien approved these changes

2024-04-16 11:35 UTC, wattnpapa commented
Is here any blocker or why it is not merged?

2024-04-22 07:11 UTC, mmequignon approved these changes

2024-05-03 07:58 UTC, dreispt commented
/ocabot merge nobump

2024-05-03 08:05 UTC, merged