[16.0][FIX] partner_multi_relation: fix name search on relation
OCA/partner-contact pull request #1740
Opened 2024-04-18 13:15 UTC by NL66278

Before this fix the following exception was logged (and the search not done):
```
2024-04-18 13:13:15,110 320 ERROR vwnvrs-testdatabase odoo.osv.expression: Non-stored field res.partner.relation.type.selection.display_name cannot be searched. 
NoneType: None
```

After fix no more errors in the log and the search works.

2024-08-27 09:16 UTC, SirAionTech commented
Could you please explain how to obtain this error?
I tried to search for a relation in its `Many2one` field but the search is performed correctly and no ERROR is logged.

2024-08-27 10:12 UTC, NL66278 commented
@SirAionTech The error occurs if you have a model with a Many2one field to res.partner.relation.all, and then in the form you enter a name to search on.

2024-08-27 10:41 UTC, SirAionTech requested changes
Thanks for the PR!
I had a look at the code and tested this change as you suggested in https://github.com/OCA/partner-contact/pull/1740#issuecomment-2312116188:
> The error occurs if you have a model with a Many2one field to res.partner.relation.all, and then in the form you enter a name to search on.

Everything looks fine.

Could you please add a test that fails without this fix? Searching for records is a feature I'd say is worth protecting from regression.

2024-12-30 08:31 UTC, NL66278 commented
@OCA-git-bot merge minor

2024-12-30 08:32 UTC, NL66278 commented
/ocabot merge minor

2024-12-30 08:36 UTC, merged