[17.0][MIG] partner_contact_access_link: Migration to 17.0
OCA/partner-contact pull request #1758
Opened 2024-05-17 11:58 UTC by Tisho99

Supersedes #1649

Cleared commit history 

T-6069

2024-05-17 12:01 UTC, pedrobaeza commented
/ocabot migration partner_contact_access_link

2024-05-17 13:08 UTC, Tisho99 commented
@ValentinVinagre @HaraldPanten

2024-05-17 13:10 UTC, Tisho99 commented
@CRogos 

I have cleared commit history as you suggested in #1649

2024-05-17 13:19 UTC, CRogos requested changes

2024-05-17 13:19 UTC, CRogos commented on base_partner_sequence/README.rst
Can you remove the changes form base_partner_sequence

2024-05-21 07:16 UTC, Tisho99 commented on base_partner_sequence/README.rst
Done!

2024-05-21 08:02 UTC, CRogos approved these changes
Code + Function LGTM

2024-05-21 08:29 UTC, HaraldPanten approved these changes
LGTM

2024-05-21 08:29 UTC, HaraldPanten commented
/ocabot merge nobump

2024-05-21 08:35 UTC, merged