[16.0][FIX] translate partner name order config values
OCA/partner-contact pull request #1829
Opened 2024-08-01 08:47 UTC by benwillig

2024-08-26 15:10 UTC, SirAionTech requested changes
Thanks for the PR!
Please mention the changed module so that it follows the guidelines
> commit messages should be self explanatory (long enough) including the name of the module that has been changed

(from https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message)

2024-08-26 15:10 UTC, SirAionTech commented on partner_firstname/i18n/fr.po
`.po` files should not be edited in PRs
> Pull requests should never directly modify ``.po`` files, because this could produce merge conflicts with pushes coming from weblate.

(from https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#11translations)

I think this also applies to `.pot` files.

2024-08-26 15:10 UTC, SirAionTech commented on partner_firstname/models/base_config_settings.py
> +            ("first_last", _("Firstname Lastname")),
Just adding a bit of technical background: when the `selection` attribute of a field requires to call a method, the labels in its result are not translated:
```py
        if isinstance(selection, str) or callable(selection):
            return determine(selection, env[self.model_name])

        # translate selection labels
        if env.lang:
            return env['ir.model.fields'].get_field_selection(self.model_name, self.name)
        else:
            return selection
```
(from https://github.com/odoo/odoo/blob/38ec36e9b5dde0c02a4ff47714b1056e0db76812/odoo/fields.py#L2701-L2708)

2024-08-28 07:31 UTC, benwillig commented
Removed translations and updated commit message.

> A test would be nice too

I don't think I should test this

2026-09-01 15:24 UTC, yvaucher reviewed
LGTM

2026-09-04 10:00 UTC, yvaucher commented
/ocabot merge patch

2026-09-04 10:18 UTC, merged