[16.0][MIG] partner contact in several companies: Migration to 16.0
OCA/partner-contact pull request #1852
Opened 2024-10-01 11:14 UTC by stephansainleger

new PR replacing PR #1703 (wrong git manipulation...)

2024-10-01 12:23 UTC, stephansainleger commented
Hi @legalsylvain !
After several misadventures with Git (including the unintentional closure of PR [#1703](https://github.com/OCA/partner-contact/pull/1703) ...), I was finally able to properly follow the migration procedure for the module partner_contact_in_several_companies.
Could you please let me know if everything is OK so we can finally complete this migration?
Thank you!

2024-10-04 08:33 UTC, PicchiSeba commented
I think we should take advantage of this occasion to comply with OCA module documentation.

The file README.md added in 9d8a0b2f093ffae0e56436d1598be49dea45d9a4 should be generated automatically.
To do so we should move it to a directory called `readme` and change the extension from `.md` to `.rst`.
In the same directory we should create two files called `CONTRIBUTORS.rst` and `USAGE.rst`, in the latter we must move the "Usage" section from README.rst

Then we can regenerate the "README.rst" file in the root folder with `oca-gen-addon-readme`

2024-10-21 12:49 UTC, aleuffre requested changes
Hello, thank you for the PR!

Just a small warning

2024-10-21 12:49 UTC, aleuffre commented on partner_contact_in_several_companies/models/res_partner.py
> +        return super(ResPartner, modified_self).create(vals)
**issue**: When I install the module, I have this warning:

```
WARNING devel odoo.api.create: The model odoo.addons.partner_contact_in_several_companies.models.res_partner is not overriding the create method in batch 
```

It's probably enough to just change the decorator to `@api.model_create_multi`

2024-10-21 14:46 UTC, rousseldenis commented
/ocabot migration partner_contact_in_several_companies

2024-11-04 16:09 UTC, tobru commented
Thank you so much for taking the time to migrate this add-on to Odoo 16. I just gave this PR a try in our Odoo 16, and it worked well so far. What I have seen is that in a Standalone contact in the "Other Positions" tab, the formatting seems to have some issues:

![Screenshot_20241104_170303](https://github.com/user-attachments/assets/4a66da2f-c415-4983-9f26-276853ef14b8)

* There is an artificial "Avatar" showing, I'd expect either nothing or a dummy avatar
* The line above the blurred name is empty and the "x" is placed at a strange place

Additionally, when clicking on this contact in the "Other Positions" tab, the pop-up is not really helpful, there is no mentioning to which other record this contact is related to. But maybe this was already the case in older versions and not related to the migration.

![Screenshot_20241104_170644](https://github.com/user-attachments/assets/2449310d-7b54-4659-be1f-a6ae771ebee7)

2025-03-14 21:36 UTC, stephansainleger commented on partner_contact_in_several_companies/models/res_partner.py
> +        return super(ResPartner, modified_self).create(vals)
Thanks @aleuffre for the notice, I have corrected this issue: https://github.com/OCA/partner-contact/pull/1852/files#diff-bc484720a893a4002fc161049b55f9f26bdc7a310e9dfdc656a5d32c7ce9a3c1R74

2025-03-14 21:39 UTC, stephansainleger commented
@tobru Thanks for your remarks. I have corrected:
- the image issue
- the cross (I have removed it as it comes from older versions and is not consistent anymore with similar displays)
For the pop-up, I prefer not to modify it now, as it is a deeper change not linked with the migration :-)

2025-03-17 09:45 UTC, HekkiMelody approved these changes
Code review, LGTM

2025-03-24 22:10 UTC, stephansainleger commented
Hi @pedrobaeza ! 
I read [here](https://oca.github.io/repo-maintainer-conf/teams.html#crm-sales-marketing-maintainers-psc-representative) that you might be the guy to tag for this PR final integration. Is that correct? 
Thanks ! :-)

2025-03-25 07:48 UTC, pedrobaeza submitted a review, later dismissed
Please don't have README.md and README.rst. It should be README.rst for proper parsing inside Odoo, and you can make use of the fragments inside `readme` folder for letting the pre-commit hook to generate a complete README.rst file.

2025-03-25 09:30 UTC, stephansainleger commented
> Please don't have README.md and README.rst. It should be README.rst for proper parsing inside Odoo, and you can make use of the fragments inside `readme` folder for letting the pre-commit hook to generate a complete README.rst file.

Thanks @pedrobaeza ! I have pushed a new `READED.rst` and removed the `.md`. I had issues with pre-commit locally, so I still only have the README.rst file, without the `readme` repo. Is that OK for you? :-)

2025-03-25 09:44 UTC, HekkiMelody commented
> > Please don't have README.md and README.rst. It should be README.rst for proper parsing inside Odoo, and you can make use of the fragments inside `readme` folder for letting the pre-commit hook to generate a complete README.rst file.
> 
> Thanks @pedrobaeza ! I have pushed a new `READED.rst` and removed the `.md`. I had issues with pre-commit locally, so I still only have the README.rst file, without the `readme` repo. Is that OK for you? :-)

Even if you have trouble with pre-commit, you can generate a Readme using `oca-gen-addon-readme` which is ultimately what pre-commit does anyway.
https://github.com/OCA/maintainer-tools/?tab=readme-ov-file#readme-generator

2025-05-30 15:44 UTC, stephansainleger commented
@aleuffre @pedrobaeza I finally manage to propose a README file accepted by pre-commit :sweat_smile: 
All checked being passed, could you please perform final step ?
Thks for your advice! :pray:

2025-05-30 15:46 UTC, pedrobaeza commented
/ocabot migration partner_contact_in_several_companies

2025-05-31 12:00 UTC, stephansainleger commented
Hi @pedrobaeza, it seems a review is still expecting from you :-)

2025-05-31 13:27 UTC, pedrobaeza commented
Hi, I abstain from reviewing, as I don't use this module (nor recommend it). I just did a review on the "form thing", and now I have dismissed it.

2025-06-18 13:49 UTC, njeudy approved these changes
Code review and real test on prod databases

2025-06-30 12:45 UTC, stephansainleger commented
Hi @pedrobaeza !
It seems all the required checks and reviewed are done. Could you, or another core maintainer, please merge this PR?
Thanks a lot ! :pray:

2025-06-30 15:21 UTC, pedrobaeza commented
OK, a PSC hasn't reviewed it, but having some old contributors like Nicolas here, let's merge it.

/ocabot merge nobump

2025-06-30 15:33 UTC, pedrobaeza commented
It seems the fragments syntax is not correct when you combine it in the main README.rst. Check if you are using a title underlining. Only `~~~~~~` is allowed.

2025-06-30 16:25 UTC, stephansainleger commented
> It seems the fragments syntax is not correct when you combine it in the main README.rst. Check if you are using a title underlining. Only `~~~~~~` is allowed.

Indeed there was wrong underlining. It is fixed! :-)

2025-06-30 16:26 UTC, pedrobaeza commented
/ocabot merge nobump

2025-06-30 16:30 UTC, marcelsavegnago approved these changes

2025-06-30 16:35 UTC, merged

2025-06-30 16:52 UTC, stephansainleger commented
Thanks :pray: :pray:  @pedrobaeza and all others for your kind assistance, this is my first merged PR in OCA, and normally not the last! :muscle: :smile: