[17.0][MIG] partner_property: Migration to version 17.0
OCA/partner-contact pull request #1864
Opened 2024-10-14 14:52 UTC by pilarvargas-tecnativa

cc @Tecnativa TT51236

@victoralmau @chienandalu please review

2024-10-14 16:03 UTC, chienandalu reviewed
Test and code :+1: Just a tiny change:

2024-10-14 16:03 UTC, chienandalu commented on partner_property/readme/USAGE.md
> +Delete property fields:
```suggestion
Add property fields:

2024-10-15 05:31 UTC, pilarvargas-tecnativa commented on partner_property/readme/USAGE.md
> +Delete property fields:
thanks!

2024-10-15 06:27 UTC, victoralmau requested changes
Functional review OK. Can you squash administrative commits?

2024-10-15 06:27 UTC, victoralmau commented on partner_property/i18n/es.po
> +#~ msgstr "Propiedades"
```suggestion
```

2024-10-15 06:27 UTC, victoralmau commented on partner_property/i18n/it.po
> +#~ msgstr "Proprietà"
```suggestion
```

2024-10-15 06:27 UTC, victoralmau commented on partner_property/views/res_partner_views.xml
> +                    invisible="is_company == False"
```suggestion
                    invisible="not is_company"
```

2024-10-15 06:27 UTC, victoralmau commented on partner_property/views/res_partner_views.xml
> +                    invisible="is_company == True"
```suggestion
                    invisible="is_company"
```

2024-10-15 08:02 UTC, pilarvargas-tecnativa commented
@victoralmau all changes done, thanks!

2024-10-15 08:07 UTC, victoralmau approved these changes

2024-10-15 08:09 UTC, chienandalu approved these changes

2024-10-15 08:12 UTC, pedrobaeza commented
/ocabot migration partner_property
/ocabot merge nobump

2024-10-15 08:19 UTC, merged