[18.0] [MIG] partner_contact_gender: Migration to 18.0
OCA/partner-contact pull request #1901
Opened 2024-11-26 16:59 UTC by Borruso

Migration from 17.0 to 18.0

2024-12-22 11:09 UTC, Sanazzzmi approved these changes

2024-12-22 11:14 UTC, mostafabarmshory approved these changes

2024-12-22 11:23 UTC, mostafabarmshory commented
@OCA-git-bot  @pedrobaeza @rousseldenis

Hello. I need this module. Please merge it for version 18 as soon as possible. Thanks

2024-12-22 11:29 UTC, Sanazzzmi commented
@OCA-git-bot @pedrobaeza @rousseldenis
Hello. Could you please assist with migrating this module? I would greatly appreciate your help.

Thank you!

2024-12-22 12:17 UTC, Sanazzzmi approved these changes

2024-12-22 12:20 UTC, Sanazzzmi requested changes
Please replace Git Links with PyPI Versions in test-requirements file. Thank you

2024-12-22 12:20 UTC, Sanazzzmi commented on test-requirements.txt
Please replace Git Links with PyPI Versions. Thank you

2024-12-22 12:26 UTC, mostafabarmshory requested changes
@Borruso 
Hello. Please check the test-requirements.txt file and remove the git address in this file. Thank you.

2024-12-22 12:41 UTC, Borruso commented
> @Borruso Hello. Please check the test-requirements.txt file and remove the git address in this file. Thank you.

Hello @mostafabarmshory,
yes I can remove test-requirements.txt, 
but partner_contact_personal_information_page is not yet merged.
If I remove checks it will turn red.

2024-12-22 15:31 UTC, pedrobaeza commented
Dependency merged. Anyway, @mostafabarmshory, you can use existing PRs for your deployments with tools like git-aggregator or pip+git nomenclature. Not always making us ping will have effect.

2024-12-23 08:13 UTC, pedrobaeza commented
/ocabot migration partner_contact_gender

2025-01-16 08:45 UTC, rousseldenis approved these changes

2025-01-16 10:56 UTC, leemannd reviewed
Technically correct. But shouldn't old translations commit be squashed together?

2025-04-21 08:44 UTC, BT-mlopez approved these changes

2025-05-30 10:29 UTC, jeromeguerriat-msf commented
@mostafabarmshory @Sanazzzmi it appears you review were requested. Could you check? 

Thank you :-)

2025-06-05 18:02 UTC, mostafabarmshory approved these changes

2025-06-05 18:04 UTC, marcelsavegnago approved these changes
LGTM

2025-06-08 07:46 UTC, Sanazzzmi approved these changes

2025-06-08 07:49 UTC, rvalyi commented
/ocabot merge nobump

2025-06-08 07:56 UTC, merged