[18.0][MIG] partner_disable_gravatar
OCA/partner-contact pull request #1940
Opened 2024-12-23 10:00 UTC by alexis-via

Simple migration from v17 to v18. No changes in the code. Tested, works well.

2024-12-23 17:18 UTC, amh-mw requested changes
It looks like the `[MIG] Migration to 18.0` commit got squashed into the `[IMP] pre-commit auto fixes` commit?

2024-12-23 23:27 UTC, alexis-via commented
@amh-mw There is 0 code change for v18 migration compared to the code in v17.

2024-12-24 03:49 UTC, rvalyi approved these changes

2024-12-24 10:34 UTC, pedrobaeza reviewed
The commit message should be:

```
[MIG] partner_disable_gravatar: Migration to 18.0
```

not `[IMP]`

2025-02-01 14:26 UTC, alexis-via commented
/ocabot merge nobump

2025-02-17 22:52 UTC, alexis-via commented
/ocabot merge nobump

2025-02-17 22:58 UTC, merged