[ADD] New module partner_firstname_auth_ldap
OCA/partner-contact pull request #282
Opened 2016-06-20 10:45 UTC by lmignon

2016-06-20 10:50 UTC, hbrunn commented on partner_firstname_auth_ldap/models/res_company_ldap.py
> +            'email': ldap_entry[1]['mail'][0],
isn't this already taken care of by https://github.com/OCA/server-tools/blob/8.0/users_ldap_mail/users_ldap_model.py ?
And did you consider making the values configurable as the mail module does it?

2016-06-20 10:56 UTC, lmignon commented on partner_firstname_auth_ldap/models/res_company_ldap.py
> +            'email': ldap_entry[1]['mail'][0],
@hbrunn Thank you for the review. I'm not aware of `users_ldap_mail`. I'll take the same approach in this module to stay consistent...

2016-06-20 10:59 UTC, hbrunn commented on partner_firstname_auth_ldap/models/res_company_ldap.py
> +            'email': ldap_entry[1]['mail'][0],
you might also have a look at https://github.com/OCA/server-tools/tree/8.0/users_ldap_push
What I planned back then was to split this up into two modules, one taking care of the mapping from ORM fields to ldap attributes, and the second to do the actual push. But unfortunately, time constrains didn't permit this.

2016-06-20 12:00 UTC, lmignon commented on partner_firstname_auth_ldap/models/res_company_ldap.py
> +            'email': ldap_entry[1]['mail'][0],
Indeed `users_ldap_push` seems to provide a good way to define the mapping between the LDAP and the ORM. I agree with you, the module should be split into two modules but as for you, I also have time constrains.

2016-06-20 12:03 UTC, hbrunn commented on partner_firstname_auth_ldap/models/res_company_ldap.py
> +            'email': ldap_entry[1]['mail'][0],
we'll add that sooner or later. For now, having the attributes configurable as in users_ldap_mail is perfectly fine I think.

2019-04-15 21:09 UTC, NL66278 commented on partner_firstname_auth_ldap/__init__.py
> +from . import models
Missing coding and licence

2019-04-15 21:10 UTC, NL66278 commented on partner_firstname_auth_ldap/__openerp__.py
> +    'summary': """
Summary should fit one line (do not use triple quotes)

2019-04-15 21:11 UTC, NL66278 commented on partner_firstname_auth_ldap/__openerp__.py
> +    'website': 'https://acsone.eu/',
```https://github.com/oca/partner-contact```

2019-04-15 21:11 UTC, NL66278 commented on partner_firstname_auth_ldap/models/__init__.py
> +from . import res_company_ldap
coding and licence

2019-04-15 21:15 UTC, NL66278 commented
Need to add ldap to requirements.txt to solve travis errors.

2019-04-15 21:16 UTC, NL66278 requested changes
See other comments. Need to fix travis errors.

2019-08-09 07:28 UTC, NL66278 commented
@lmignon Can this be closed, or would you still like to take up the comments?

2019-12-23 01:10 UTC, NL66278 commented
Closing for lack of action.

2019-12-23 01:10 UTC, closed without merging