[8.0] Add module to manage GLN partner identification number
OCA/partner-contact pull request #298
Opened 2016-08-08 08:09 UTC by rousseldenis

Depends on [PR #296 ](https://github.com/OCA/partner-contact/pull/296)

2016-10-25 09:57 UTC, rousseldenis commented
@lmignon @andhit-r Don't hesitate to review !
@pedrobaeza Can you add label need review ?

2016-10-25 10:55 UTC, andhit-r requested changes
@rousseldenis thank you for your contributions. You might wanna check your commit history. There are a lot of file changes that is not supposed to happend.

2016-10-25 11:33 UTC, rousseldenis commented
@andhit-r Solved!

2016-10-26 14:13 UTC, andhit-r requested changes
Functional: No test
Code: minor comments inline

2016-10-26 14:13 UTC, andhit-r commented on partner_identification_gln/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/partner-contact/8.0
Wrong runbot link

2016-10-26 14:13 UTC, andhit-r commented on partner_identification_gln/__openerp__.py
> +    'demo': [
Remove empty key

2016-10-26 14:13 UTC, andhit-r commented on partner_identification_gln/static/description/icon.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Why do you use .svg not .png file?

2016-10-26 14:21 UTC, rousseldenis commented on partner_identification_gln/static/description/icon.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
@andhit-r Both apparently accepted as in module template https://github.com/OCA/maintainer-tools/tree/master/template/module/static/description

2016-10-26 14:26 UTC, rousseldenis commented
@andhit-r Changes done!

2016-10-28 00:28 UTC, andhit-r approved these changes
:+1:

2016-11-28 10:04 UTC, rousseldenis commented
@lmignon A little thumb up ? ;-)

2016-12-03 00:53 UTC, andhit-r commented
@mikevhe18 @azmimr67 please help review. Thanks

2016-12-03 06:56 UTC, lmignon requested changes

2016-12-03 06:56 UTC, lmignon commented on partner_identification_gln/models/partner.py
> +                                        ('partner_id.active', '=', True)])
Active test is by default into domain. Am I wrong?

2016-12-03 06:56 UTC, lmignon commented on partner_identification_gln/models/partner.py
> +                                        ('name', '=', id_number.name),
The search for duplicate should be put in a dedicated method to avoid code duplication with line 32

2016-12-05 08:27 UTC, rousseldenis commented on partner_identification_gln/models/partner.py
> +                                        ('partner_id.active', '=', True)])
We are not on the base model but on comodel (we don't search on res.partner).
If a partner is inactive, the search will return its numbers. We don't want this behaviour.

2016-12-05 09:18 UTC, rousseldenis commented
@lmignon that's because the context is not exactly the same.

In one case we have an EAN, in the other not.
And the cases concern different categories of id_numbers (we can have one of each in one partner).

2017-05-02 08:39 UTC, azmimr67 commented
👍testes

2017-05-29 13:52 UTC, rafaelbn commented
Hi @lmignon , could you please unblock this PR? thanks! 😄

2017-05-29 14:25 UTC, lmignon approved these changes
@rafaelbn OK for me :smirk:

2017-05-29 23:33 UTC, pedrobaeza commented
Please squash at your taste

2017-05-30 09:17 UTC, rafaelbn commented
Could I squash ?

2017-05-30 09:18 UTC, rafaelbn approved these changes
Tested in runbot

2017-05-31 09:21 UTC, rafaelbn commented
Hi @rousseldenis are you going to squash please? thanks

2017-05-31 09:24 UTC, lmignon commented
@rafaelbn @rousseldenis I'll squash

2017-05-31 09:27 UTC, lmignon commented
@rafaelbn Squash done.

2017-05-31 14:03 UTC, merged