[LICENSE] relicensing to LGPL
OCA/partner-contact pull request #323
Opened 2016-11-02 14:46 UTC by blaggacao

Hello, I kindly request evaluating to agree in relicensing base_location to LGPL. It is a very basic module, and one of the OCA objectives is to foster code reusability across OCA repos. This module is so basic, that is is very easy to become infected down the line. On the other hand it is a very useful module for localisation repositories. Being still AGPL, it cannot be reused by LGPL localisations.

Thanks for your consideration! It's not too many so I guess, eventually this is feasible, until then, some people, including me are forced to reimplement the logic or similar independently under LGPL.

- [ ] @alejandrosantana 
- [ ] @tafaRU 
- [ ] @gurneyalex 
- [ ] @alexis-via 
- [ ] @bwrsandman 
- [ ] franco.tampieri
- [ ] @hhgabelgaard 
- [ ] @eLBati 
- [ ] @nbessi 
- [ ] @pedrobaeza 
- [ ] @jjscarafia 
- [ ] @sbidoul 
- [ ] @yvaucher

2016-11-02 15:03 UTC, rafaelbn commented
Hi @blaggacao , you should write to contributors@odoo-community.org

2016-11-02 17:08 UTC, eLBati commented
Hi @blaggacao , to avoid future conflicts, These changes should be proposed to https://github.com/OCA/partner-contact/pull/317

About moving to LGPL, I am OK with that

2016-11-03 08:52 UTC, yvaucher commented
I personally disagree for this relicensing without more input. What kind of module would require to have a proprietary license on top on this? If you want to sell a module you can still do it in AGPL or if it is something specific you are not forced to reverse it to the community, just to the users who uses it.

Furthermore, base location implements a very basic feature for countries that should really be available for everyone in each country, I don't want to open the door to have dozen of partner doing the exact same work for the same country and publish it on apps.odoo.com while they could collaborate.

For me LGPL makes more sense for website modules as you probably want to not having to give the code to all visitors. But for backend usage the user must be able to ask for the code source thus it should be AGPL.

2016-11-03 10:05 UTC, yvaucher requested changes
I disagree

2016-11-03 11:56 UTC, Yajo commented
> For me LGPL makes more sense for website modules as you probably want to not having to give the code to all visitors. But for backend usage the user must be able to ask for the code source thus it should stay AGPL.

Just think that you cannot create a LGPL addon as long as an AGPL one is in its inheritance chain, that's why @blaggacao asks for base addon on LGPL.

Not pressuring you, just clarifying a little bit. If you still don't agree, just say it and we'll close this.

2016-11-03 12:42 UTC, blaggacao commented
It's ok, I don't want to question motives. Odds have been limited since the beginning, that all would agree. I guess for this specific module, and strategically speaking, inclusion into upstream 11.0 could be a possible solution. On the other hand, technically, creating a siblings module partner_location_lgpl would be warranted. But let's just not take this too far. I guess I have tried what's possible to be able to reuse the code - according to OCA's objectives. Now, I would simply not use it. 👋

2016-11-03 12:42 UTC, closed without merging

2016-11-03 12:56 UTC, Yajo commented
If I were you, I'd simply publish my work under AGPL for OCA and be happy with that...

2016-11-03 13:01 UTC, blaggacao commented
Yes, I understand that many people ask themselves, why is this not an option. In short: I want to take licensing seriously given our strategic options and threads. And I think that's ok.

Furthermore, it's just as respectable to go with LGPL as it is to not to do so.
Or in your words: I unfortunately can't be "happy" with AGPL. But that's ok. I'm not feeling bad about it.

2016-11-16 11:18 UTC, eLBati commented
> Just think that you cannot create a LGPL addon as long as an AGPL one is in its inheritance chain

Actually, you can, as LGPL 3 is GPL-compatible.
See
https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL
and
https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

2016-11-16 13:30 UTC, Yajo commented
Well, true you can, but under those circumstances, combination becomes fully AGPL automatically: https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility