[IMP][10.0] Partner names order configurable
OCA/partner-contact pull request #334
Opened 2016-11-14 00:31 UTC by lasley

Forward port of #227 & #333 

[IMP] Partner names order configurable
[MIG] partner_firstname: Style improvements for forward port  …
* Prefer odoo to openerp & remove data tags
* Move exceptions file out of models
* Fix string selection in xpath
* Rename res_users and add import

2016-11-14 00:36 UTC, pedrobaeza commented on partner_firstname/__manifest__.py
>                "Grupo ESOC Ingeniería de Servicios, "
I'm missing here `Tecnativa`. Antonio should forget to include it in the first place.

2016-11-14 00:38 UTC, lasley commented on partner_firstname/__manifest__.py
>                "Grupo ESOC Ingeniería de Servicios, "
Added in both versions

2016-11-14 00:45 UTC, pedrobaeza approved these changes
Thank you!

2016-11-14 09:49 UTC, rafaelbn requested changes
There is an error.

Go to:
- Settings > Configuration > General settings

And:

```
Odoo server error
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/addons/web/controllers/main.py", line 862, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3272270-334-94601a/odoo/addons/base/res/res_config.py", line 508, in default_get
    res.update(getattr(self, method)(fields))
TypeError: get_default_partner_names_order() takes exactly 1 argument (2 given)
```

2016-11-17 13:34 UTC, susport commented on partner_firstname/models/base_config_settings.py
> +from openerp import models, fields, api
Order by name the import, about the Odoo guidelines.

2016-11-17 13:55 UTC, susport commented on partner_firstname/models/base_config_settings.py
> +    partner_names_order_changed = fields.Boolean(
In compute method not necessary att readonly=True

2016-11-30 01:37 UTC, lasley commented
Thanks for the reviews @rafaelbn & @susport. All notes attended to, this should be good to go assuming CI passes

2016-11-30 11:01 UTC, rafaelbn commented
Hi @lasley , something happends with the "recaltulate names" button. It doesn't appear in 2/3 options and the icon is broken.

![2016-11-30_12-00-07](https://cloud.githubusercontent.com/assets/8736623/20749945/c0df5972-b6f4-11e6-9ab6-b4ad1b9743aa.png)

Thanks

2016-12-03 01:41 UTC, susport approved these changes
👍

2017-01-28 01:59 UTC, lasley commented
@rafaelbn - sorry I missed your comment. Icon fixed.

Regarding the missing button - the button only appears if a change needs to be made. Otherwise, it is invisible. I triggered it back and forth a few times, and it seems to work 👍

2017-01-28 03:16 UTC, lasley commented
@rafaelbn - ahhh actually I think maybe what you were seeing was a missing api.depends. I also noticed a singleton issue that may have been causing some problems. I'm pretty sure this resolved the button weirdness.

2017-02-17 22:32 UTC, lasley commented
@rafaelbn - can you please verify that I have attended to your comments?

2017-03-28 20:47 UTC, lasley commented
Is this good to merge?

2017-03-28 21:00 UTC, pedrobaeza commented
Please squash your commits and I'll proceed.

2017-03-28 21:09 UTC, lasley commented
Squashed, thanks @pedrobaeza!

2017-03-29 08:44 UTC, merged

2017-05-24 18:55 UTC, b5baxter commented
Is this working.  I am still getting errors with v10.