[ADD] partner_contact_nutrition_diet
OCA/partner-contact pull request #339
Opened 2016-11-18 17:08 UTC by max3903

#335 

Depends on #337

2016-11-21 20:01 UTC, lasley requested changes
Thanks @max3903 - comments inline

2016-11-21 20:01 UTC, lasley commented on partner_contact_nutrition_diet/__init__.py
> +from . import models
newline

2016-11-21 20:01 UTC, lasley commented on partner_contact_nutrition_diet/__openerp__.py
> +    "category": "Uncategorized",
What do you think about putting these under `Health`? Seems like we have enough modules to warrant a category

2016-11-21 20:01 UTC, lasley commented on partner_contact_nutrition_diet/data/nutrition_diet.xml
> + </odoo>
newline

2016-11-21 20:01 UTC, lasley commented on partner_contact_nutrition_diet/data/nutrition_diet.xml
> +
Vegan?

2016-11-21 20:01 UTC, lasley commented on partner_contact_nutrition_diet/models/__init__.py
> +)
newline

2016-11-21 20:01 UTC, lasley commented on partner_contact_nutrition_diet/views/res_partner_view.xml
> + </odoo>
newline

2016-11-21 22:17 UTC, susport commented on partner_contact_nutrition_diet/models/nutrition_diet.py
> +from openerp import models, fields
Please sort alphabetically according to oca guide

2016-11-21 22:18 UTC, susport commented on partner_contact_nutrition_diet/models/res_partner.py
> +from openerp import models, fields
Please sort alphabetically the import according to oca guide

2016-11-22 15:53 UTC, leemannd approved these changes
Once Comments from @lasley are fullfilled

2016-11-22 16:06 UTC, max3903 commented on partner_contact_nutrition_diet/data/nutrition_diet.xml
> +
http://www.diffen.com/difference/Vegan_vs_Vegetarian ;)

2016-11-22 16:06 UTC, max3903 commented on partner_contact_nutrition_diet/__openerp__.py
> +    "category": "Uncategorized",
ok

2016-11-22 16:40 UTC, lasley commented on partner_contact_nutrition_diet/data/nutrition_diet.xml
> +
Sorry I was suggesting that we add vegan. It's fairly common IMO

2016-11-22 17:34 UTC, lasley approved these changes
Thanks @max3903

2016-11-22 17:37 UTC, merged