[ADD] Company Registry Module
OCA/partner-contact pull request #348
Opened 2016-12-02 13:08 UTC by aschenkels-ictstudio

Add a company registry option like on res_company

2016-12-21 14:46 UTC, hbrunn requested changes

2016-12-21 14:46 UTC, hbrunn commented on partner_company_registry/README.rst
> +Partner Comapny Registry
typo

2016-12-21 14:46 UTC, hbrunn commented on partner_company_registry/__openerp__.py
> +        'view/res_partner.xml',
the folder is called `viewS`

2016-12-21 14:46 UTC, hbrunn commented on partner_company_registry/views/res_partner.xml
> +    <data noupdate="0">
remote attribute with default value

2016-12-21 14:46 UTC, hbrunn commented on partner_company_registry/views/res_partner.xml
> +            <field name="name">partner.view.form.partner_company_registry</field>
remove this field, odoo generates a name for you

2017-01-27 13:21 UTC, petrus-v requested changes

2017-01-27 13:21 UTC, petrus-v commented on partner_company_registry/README.rst
> +   :target: http://odoo-community.org
If I remember new guide lines required https links

2017-05-29 13:30 UTC, rafaelbn commented
Hi @aschenkels-ictstudio , are you going to continue this PR?  commented on 2 Dec 2016 Let us know please

2017-05-30 11:33 UTC, rafaelbn commented
7 months without answer

2017-05-30 11:33 UTC, closed without merging