[WIP][9.0][Port] mig partner changeset
OCA/partner-contact pull request #357
Opened 2016-12-07 09:58 UTC by leemannd

WIP
As https://github.com/OCA/partner-contact/pull/213 is not going forward, there is a proposition to do it here.

2016-12-07 16:21 UTC, leemannd commented
@pedrobaeza @guewen @damdam-s It is not anymore in WIP state

2016-12-07 16:27 UTC, leemannd commented on partner_changeset/security/security.xml
> +  <data>
Not sure about this one. Is it possible with `<odoo>` to have a part of the records with noupdate and a part without?

2016-12-12 14:26 UTC, jgrandguillaume approved these changes
Hi,


Functional test done, works great ! Thanks for the port :+1: 

Regards,

Joël

2016-12-12 15:02 UTC, damdam-s approved these changes

2016-12-12 16:15 UTC, pedrobaeza commented
I know I'm always asking the same, but can you squash all that useless commits from the same person?

2016-12-12 16:44 UTC, leemannd commented
@pedrobaeza I usually don't feel comfortable with modifying the git history of other people, but I'll do it in the beginning when porting a module.
Done.

2016-12-15 13:19 UTC, pedrobaeza requested changes
Little changes that you can squash with your main PR

2016-12-15 13:19 UTC, pedrobaeza commented on partner_changeset/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/134/8.0
Change this to 9.0

2016-12-15 13:19 UTC, pedrobaeza commented on partner_changeset/README.rst
> +8.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.
And remove this part according last template

2016-12-15 14:07 UTC, leemannd commented
@pedrobaeza Corrected

2016-12-15 16:59 UTC, pedrobaeza commented
Travis is failing

2016-12-15 17:27 UTC, leemannd commented
@pedrobaeza error in tests linked to the fact that cache is not updated during the same transaction. It should be better now.

2016-12-16 00:15 UTC, pedrobaeza approved these changes

2016-12-16 00:15 UTC, merged