[ADD] partner_password_reset: Create module
OCA/partner-contact pull request #369
Opened 2017-01-11 20:54 UTC by tedsalmon

* Create module that allows you to send the password reset emails from the Partner view to any associated `res.users`

cc @lasley

2017-01-24 08:51 UTC, rousseldenis reviewed
I don't know if I like this because action server is not based on groups, so this action is accessible to everyone... Is this wanted ?

2017-01-24 17:32 UTC, lasley commented
@rousseldenis - Actually yeah this was intended. Generating a password reset email actually doesn't require admin permissions. Locking it behind those permissions makes it so that when a customer requests a password reset, an admin has to do it, or the customer has to be walked through the process of doing it themselves. While self-help is obviously ideal, most customer in pharmacy (old people) absolutely refuse to do so.

@tedsalmon That said, I think this should be modularized a bit. While this code works fine when you're making a feature for a customer on the fly, this is totally unrefined right now. I don't think a server action is a good solution for a permanent module.

IMO we should inject the button using proper xpath & use real model methods to perform this.

2017-01-25 21:59 UTC, tedsalmon commented
Hey @lasley  / @rousseldenis,

I've converted this into a proper action inside a module. Let me know if there's anything else required.

Thanks!

2017-01-25 22:23 UTC, lasley requested changes

2017-01-25 22:23 UTC, lasley commented on partner_password_reset/models/res_partner.py
> +            rec.user_ids.action_reset_password()
`user_ids` is not a partner attr

2017-01-25 22:23 UTC, lasley commented on partner_password_reset/models/res_partner.py
> +        for rec in self:
self.mapped('user_id').action_reset_password()

2017-01-25 22:35 UTC, tedsalmon commented on partner_password_reset/models/res_partner.py
> +            rec.user_ids.action_reset_password()
Yes it is, please see:

https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_partner.py#L246

`user_id` is definitely not the droid I'm looking for:
https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/res/res_partner.py#L198

😆

2017-01-25 22:39 UTC, tedsalmon commented
Thanks for the review! Comments have been responded or attended to :)

2017-01-26 01:47 UTC, lasley commented
I think maybe we still need some ACLs though, as mentioned in https://github.com/OCA/partner-contact/pull/369#issuecomment-274876333

> On the note of security too, we should definitely only show this to employees.

2017-01-26 09:41 UTC, rousseldenis commented
@lasley IMO, having base.group_user on button is sufficient. Agree ?

2017-01-26 17:30 UTC, lasley commented
@rousseldenis Totally agree, `base.group_user` is perfect for the intent here!

2017-01-26 19:39 UTC, tedsalmon commented
Cool, that's the group already assigned to the button :)!

2017-01-26 19:50 UTC, lasley approved these changes
Oh snap my bad, I dunno how i missed that! 

LGTM, thanks

2017-01-27 08:01 UTC, rousseldenis approved these changes
:+1:

2017-04-25 16:14 UTC, hparfr commented
Good work.
+1 for the feature available for backend users.

But the button is always visible, even if there is no user linked to the partner.

2017-04-25 16:18 UTC, tedsalmon commented
@hparfr,

Interesting, I'll take a look at the domain on the button and adjust as necessary.

Thanks!

2017-04-25 18:01 UTC, lasley commented
@tedsalmon while you're there can you please attend to @elicoidal comments in #383, then cross port all the things?

2017-04-26 23:46 UTC, tedsalmon commented
@hparfr,

That was a doozy! It should now be fixed though, so please take a look when you have a chance.

@lasley,

Comments in #383 have been attended to in this PR. I'll cross port now!

Thanks!

2017-04-27 09:10 UTC, hparfr approved these changes

2017-05-03 21:47 UTC, tedsalmon commented
Per https://github.com/OCA/partner-contact/pull/383#issuecomment-299045172, I have turned the functionality added in this module into a wizard. I'll squash commits once these changes are approved.

Thanks!

2017-05-04 15:04 UTC, lasley requested changes

2017-05-04 15:04 UTC, lasley commented on partner_password_reset/wizard/res_partner_password_reset_wizard.py
> +        return res
This untested line makes me sad panda

2017-05-04 15:04 UTC, lasley commented on partner_password_reset/wizard/res_partner_password_reset_wizard.py
> +            rec.user_ids.action_reset_password()
`self.mapped('user_ids').action_reset_password()` instead of record loop.

Also there's a panda here too

2017-05-04 21:47 UTC, tedsalmon commented
@lasley,

Thanks for the review - comments attended to.

2017-05-05 01:32 UTC, lasley approved these changes

2017-05-29 10:26 UTC, chienandalu approved these changes

2017-05-29 10:48 UTC, merged