[IMP] partner_identification: Add context override
OCA/partner-contact pull request #373
Opened 2017-01-21 22:17 UTC by lasley

* Allow for context override of validations using ``__id_no_validate__``

This was causing me some issues with an importer, where all data may not be good but is still required.

2017-01-23 16:27 UTC, rousseldenis approved these changes
:+1:  Code review

2017-01-23 16:31 UTC, pedrobaeza commented
You can put as context variable only `id_no_validate` for being shorter and clearer to pass the value I think.

2017-01-23 16:57 UTC, lmignon commented
@lasley I also prefer `id_no_validate` as key.   Apart from your proposal makes sense.

2017-01-23 17:49 UTC, lasley commented
I prefer that naming as well. Done!

2017-01-23 17:54 UTC, pedrobaeza approved these changes

2017-01-24 08:20 UTC, lmignon requested changes

2017-01-24 08:20 UTC, lmignon commented on partner_identification/README.rst
> +  overridden by setting ``__id_no_validate__`` to ``True`` in the context, such as:
@lasley  s/__ id_no_validate __/id_no_validate

2017-01-24 17:44 UTC, lasley commented
Thanks for the catch @lmignon, ReadMe updated

2017-01-24 17:51 UTC, lmignon approved these changes
Thank you @lasley

2017-01-24 17:55 UTC, merged