feat(res.partner): add field birthdate_month
OCA/partner-contact pull request #420
Opened 2017-05-21 01:31 UTC by agb80

Add field birtdate_month that allow create a new filter to display only res.partners which birthdate

is on current month.

2017-05-29 08:36 UTC, antoniocanovas commented
Hi @rafaelbn I see two entries in advanced search called "Birthday" on runbot.
The filter for "birthday this month" works fine.

2017-05-29 08:41 UTC, antoniocanovas commented
@rafaelbn , I go on testing...
The advanced filter for "Birthday month" works with numbers.
It would be fine to can search by the name of the month too, or advise to use only numbers.

2017-05-29 09:27 UTC, aming27 commented
I test the functionability and works fine.

2017-05-29 09:51 UTC, chienandalu commented
Is this PR too specific in its purpose?

2017-05-30 02:29 UTC, agb80 commented
@chienandalu the purpose for this PR is being able to get a list for customers whose birthday is this month for being able to send them promotions. 

@antoniocanovas the two birthdate fields are already present on partner_bitthday module before this PR, didn't change it because I think will be out of scope and will need an independent PR if needed.

2017-05-30 08:24 UTC, AaronHForgeFlow reviewed
It works fine. However, In my opinion it'd be more useful if the system tell us in advance when is the birthday. With this approach it would be too late for the contacts whose birthday falls on the first day of the month.

2017-05-30 08:57 UTC, rafaelbn commented
Hi @agb80 , sorry but in this case this module makes something very specific. This is not a general improvement for OCA. Furthermore you don't need to add this field yo get this information, you just have yo add and option with a "Group by" date in the field birthday to get the same information. Or just you can add that filter of "This month birthdays" using same field birthday without adding a new fields... It's just a formula... I'm closing.

2017-05-30 12:57 UTC, rafaelbn commented
Hi  @agb80 , after a discussion here in the Code Sprint we have reconsider you PR.

Please add a group by also, it would be useful to group by month too.

Thanks

2017-06-22 20:11 UTC, lasley requested changes

2017-06-22 20:11 UTC, lasley commented on partner_contact_birthdate/models.py
> +            self.birthdate_month = datetime.strptime(
`fields.Datetime.from_string`

2017-06-22 20:11 UTC, lasley commented on partner_contact_birthdate/views/res_partner.xml
> +            <filter string="This month birthdates" name="this_month_birthdates" domain="[('birthdate_month','=', context_today().strftime('%%m'))]"/>
s/This month birthdates/Birthdays This Month

2019-12-23 01:15 UTC, NL66278 commented
This seems very specific to me and not a general improvement. Anyway, would you take up the change request and resolve the conflicts?

2019-12-28 19:05 UTC, NL66278 commented
Branch contains conflicts and question is not taken up.

2019-12-28 19:05 UTC, closed without merging