[MIG] partner_contact_department: Migration to 10.0
OCA/partner-contact pull request #425
Opened 2017-05-29 15:24 UTC by chienandalu

- Minor migration tweaks

cc @Tecnativa

2017-05-30 11:42 UTC, yajo approved these changes
Code OK, please squash by logical changeset and author.

2017-05-31 11:44 UTC, rafaelbn approved these changes
Tested functionally in trunbot

2017-05-31 11:46 UTC, rafaelbn approved these changes

2017-05-31 11:46 UTC, rafaelbn commented on partner_contact_department/README.rst
> +* Pedro M. Baeza <pedro.baeza@serviciosbaeza.com>
pedro.baeza@tecnativa.com

2017-05-31 11:46 UTC, rafaelbn commented on partner_contact_department/README.rst
> +* Antonio Espinosa <antonioea@antiun.com>
antonio.espinosa@tecnativa.com

2017-05-31 11:46 UTC, rafaelbn commented on partner_contact_department/README.rst
> +* Rafael Blasco <rafabn@antiun.com>
rafael.blasco@tecnativa.com

2017-05-31 11:46 UTC, rafaelbn commented on partner_contact_department/README.rst
> +* Jairo Llopis <yajo.sk8@gmail.com>
jairo.llopis@tecnativa.com

2017-05-31 12:54 UTC, chienandalu commented
Please, @rafaelbn review last changes to rebase and merge

2017-05-31 13:14 UTC, luismontalba approved these changes
Its OK

2017-05-31 13:17 UTC, yajo requested changes

2017-05-31 13:17 UTC, yajo commented on base_location_nuts/__manifest__.py
>      'name': 'NUTS Regions',
Why is `base_location_nuts` included in this PR?

2017-05-31 13:31 UTC, chienandalu commented
@Yajo Sorry, I merged two branches :sweat: fixed!

2017-05-31 14:02 UTC, yajo approved these changes
code review

2017-05-31 14:02 UTC, Yajo commented on partner_contact_department/models/res_partner.py
> +        oldname="children")
You can drop the oldname if it was already there in the last version.

2017-05-31 14:26 UTC, chienandalu commented on partner_contact_department/models/res_partner.py
> +        oldname="children")
Done!

2017-05-31 14:32 UTC, rafaelbn commented
Please @chienandalu squash for merge thanks!

2017-05-31 14:54 UTC, merged