[MIG] partner_employee_quantity: Migration to 10.0
OCA/partner-contact pull request #426
Opened 2017-05-29 16:22 UTC by chienandalu

- Minor migration tweaks

cc @Tecnativa

2017-05-30 11:40 UTC, yajo approved these changes
Code OK, please squash by logical changeset/author.

2017-05-31 11:47 UTC, rafaelbn requested changes

2017-05-31 11:47 UTC, rafaelbn commented on partner_employee_quantity/README.rst
> +* Antonio Espinosa <antonioea@antiun.com>
antonio.espinosa@tecnativa.com

2017-05-31 11:47 UTC, rafaelbn commented on partner_employee_quantity/README.rst
> +* Jairo Llopis <yajo.sk8@gmail.com>
jairo.llopis@tecnativa.com

2017-05-31 11:47 UTC, rafaelbn commented on partner_employee_quantity/__manifest__.py
> +    "author": "Antiun Ingeniería S.L., Odoo Community Association (OCA)",
Add Tecnativa

2017-05-31 11:47 UTC, rafaelbn commented on partner_employee_quantity/__manifest__.py
> +    'website': 'http://www.antiun.com',
www.tecnativa.com

2017-05-31 13:14 UTC, chienandalu commented
@rafaelbn You review now to rebase and merge

2017-05-31 14:55 UTC, rafaelbn approved these changes

2017-06-02 08:54 UTC, chienandalu commented
Not sure of why Travis is failing

2017-06-02 09:49 UTC, Yajo commented
It's #434

2017-06-08 16:58 UTC, pedrobaeza commented
Please rebase to get a green branch

2017-06-09 00:15 UTC, merged