[MIG] partner_capital: Migration to 10.0
OCA/partner-contact pull request #427
Opened 2017-05-30 08:08 UTC by chienandalu

- Minor migration tweaks

cc @Tecnativa

2017-05-30 11:26 UTC, yajo approved these changes
Please squash all my commits in 1, all Transbot's + en.po removal in 1, and yours in 1. 3 in total.

2017-05-30 14:41 UTC, angelmoya approved these changes
Small remark, but it's OK

2017-05-30 14:41 UTC, angelmoya commented on partner_capital/README.rst
> +country of origin of capital, registered capital amount and turnover.
On code "registered capital" was renamed as "Capital amount", maybe could be better to update also in README

2017-05-31 11:49 UTC, rafaelbn requested changes

2017-05-31 11:49 UTC, rafaelbn commented on partner_capital/README.rst
> +* `Antiun Ingeniería S.L. <http://www.antiun.com>`_: Icon.
Change / fix

2017-05-31 11:49 UTC, rafaelbn commented on partner_capital/README.rst
> +* Antonio Espinosa <antonioea@antiun.com>
antonio.espinosa@tecnativa.com

2017-05-31 11:49 UTC, rafaelbn commented on partner_capital/__manifest__.py
> +    'author': 'Antiun Ingeniería S.L.',
Tecnativa + Add OCA as in templates

2017-05-31 11:49 UTC, rafaelbn commented on partner_capital/__manifest__.py
> +    'website': 'http://www.antiun.com',
www.tecnativa.com

2017-05-31 13:05 UTC, chienandalu commented
@rafaelbn Please review to rebase and merge

2017-05-31 13:11 UTC, luismontalba approved these changes

2017-05-31 14:58 UTC, rafaelbn approved these changes

2017-05-31 15:25 UTC, merged