[MIG] base_location_nuts: Migration to 10.0
OCA/partner-contact pull request #432
Opened 2017-05-31 14:20 UTC by chienandalu

cc @Tecnativa

2017-05-31 14:31 UTC, yajo requested changes

2017-05-31 14:31 UTC, yajo commented on base_location_nuts/models/res_partner.py
>      def onchange_state(self, state_id):
I'm pretty sure this kind of api is not available in v10. Please check that and use `@api.onchange` instead if possible.

2017-05-31 14:31 UTC, yajo commented on base_location_nuts/views/res_partner_view.xml
> +            <div width="1%" cell-class="oe_form_group_cell_label"
`width=1%` does something?

2017-05-31 14:31 UTC, yajo commented on base_location_nuts/views/res_partner_view.xml
> +            <div width="1%" cell-class="oe_form_group_cell_label"
Same on width

2017-05-31 14:31 UTC, yajo commented on base_location_nuts/views/res_partner_view.xml
> +            <div width="1%" cell-class="oe_form_group_cell_label"
Same on width

2017-05-31 14:31 UTC, yajo commented on base_location_nuts/views/res_partner_view.xml
> +            <div width="1%" cell-class="oe_form_group_cell_label"
Same on width.

2017-05-31 14:31 UTC, yajo commented on base_location_nuts/views/res_partner_view.xml
> +</odoo>
newline

2017-05-31 14:31 UTC, yajo commented on base_location_nuts/wizard/nuts_import.py
> +from odoo.exceptions import Warning
Import it as `UserError`; [`Warning` is deprecated.](https://github.com/odoo/odoo/blob/10.0/odoo/exceptions.py#L36-L37)

2017-05-31 14:31 UTC, yajo commented on base_location_nuts/models/res_partner.py
> +    substate = fields.Many2one(comodel_name='res.partner.nuts',
Don't you need `oldname` in these cols? Or any other migrations?

2017-06-08 16:57 UTC, pedrobaeza commented
Please rebase to get a green branch

2017-06-08 23:52 UTC, pedrobaeza commented
Waiting fixes before reviewing

2017-06-18 15:50 UTC, pedrobaeza requested changes

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/README.rst
> +To contribute to this module, please visit http://odoo-community.org.
https

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/__manifest__.py
>      'author': 'Antiun Ingeniería S.L., '
Remove Antiun

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/__manifest__.py
> +              'Tecnativa'
Comma at the end

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/__manifest__.py
> +    'website': 'http://www.tecnativa.com',
https

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/models/res_partner.py
> +        field = self["nuts%d_id" % level]
Please use `getattr(self, "nuts%_id")`

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/models/res_partner.py
> +        country_id = field.country_id.id
Don't use `.id`. You can compare directly record against record

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/models/res_partner.py
> +                if self[parent_field].id != parent_id:
Use `getattr`

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/models/res_partner.py
>      def onchange_state(self, state_id):
This method is not used anymore. Please find the equivalent one or declare a new unique onchange (`def onchange_state_id_base_location_nuts(self):`.

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/models/res_partner_nuts.py
> +        oldname="children")
There's no need of oldname in one2many fields, as they don't have a real column in the DB.

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/views/res_partner_view.xml
> +            <field name="nuts1_id"/>
Why do you remove the `attrs` attribute?

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/wizard/nuts_import.py
> +from odoo.exceptions import Warning as UserError
Old alias. Now `UserError` is the valid one.

2017-06-18 15:50 UTC, pedrobaeza commented on base_location_nuts/wizard/nuts_import.py
> +        logger.info('Importing NUTS 2013 English')
Put `...` at the end to indicate that is an operation that requires time.

2017-06-19 08:15 UTC, chienandalu commented on base_location_nuts/views/res_partner_view.xml
> +            <field name="nuts1_id"/>
I didn't. That change comes from a previous commit (https://github.com/Tecnativa/partner-contact/commit/eade50cd3ab61b354346e8bb6e227508d59008c3)

2017-06-20 16:11 UTC, pedrobaeza commented
Please increase test coverage for the onchanges and so on.

2017-06-20 17:12 UTC, chienandalu commented
I was doing some test and was getting 404 from the NUTS Eurostat server. There's some issue with Ramon not accepting https request. It does it right on http though.

2017-06-20 17:13 UTC, pedrobaeza commented
Well, change it then.

2017-06-22 10:01 UTC, chienandalu commented
@Yajo @pedrobaeza It's all green now

2017-06-23 00:08 UTC, pedrobaeza approved these changes
Remember to squash your commits before merging

2017-06-23 07:00 UTC, chienandalu commented
Commits squashed

2017-06-28 12:24 UTC, chienandalu commented
Yes, @pedrobaeza, my fault for copy-pasting and not passing flake locally prior to commit :grimacing: 
Can you review again, @Yajo ?

2017-06-28 12:28 UTC, pedrobaeza commented
Please put pre-commit linter in your git for avoiding these "surprises": https://github.com/OCA/maintainer-quality-tools/tree/master/git

2017-06-28 12:40 UTC, chienandalu commented
@pedrobaeza Thanks!

2017-07-04 07:21 UTC, yajo requested changes
Humm complex module, some suggestions to simplify it in some parts 😊 

BTW, there are some security good practices that it's good to follow, see below.

Thanks for the good job!

2017-07-04 07:21 UTC, yajo commented on base_location_nuts/models/res_partner.py
> +        field = getattr(self, 'nuts%d_id' % level)
Do not use getattr, use `self["nuts%d_id" % level]` instead.

Se slides 40 and 41: https://www.odoo.com/es_ES/slides/slide/10-rules-for-safer-code-398

2017-07-04 07:21 UTC, yajo commented on base_location_nuts/models/res_partner.py
> +        if (level - 1) > 0:
😕  Why not just `if level > 1`?

2017-07-04 07:21 UTC, yajo commented on base_location_nuts/models/res_partner.py
> +            parent_id = getattr(field, 'parent_id')
Why not `parent_id = field.parent_id`?

2017-07-04 07:21 UTC, yajo commented on base_location_nuts/models/res_partner.py
> +                parent_field = getattr(self, nuts_parent_level)
no getattr for accessing fields.

2017-07-04 07:21 UTC, yajo commented on base_location_nuts/models/res_partner.py
> +    @api.multi
All these `api.multi` can be dropped, now in v10 it's the default.

2017-07-04 07:21 UTC, yajo commented on base_location_nuts/models/res_partner.py
> +            level = int(field[:5][-1])
`level = int(field[4])`

2017-07-04 07:21 UTC, yajo commented on base_location_nuts/models/res_partner.py
> +            if level:
Not needed

2017-07-04 07:21 UTC, yajo commented on base_location_nuts/models/res_partner.py
> +        for field in fields:
You can do `for field in fields[1:]` and remove the `fields.remove` part

2017-07-04 07:21 UTC, Yajo commented on base_location_nuts/models/res_partner.py
> +            # state = self.env['res.country.state'].browse(self.state_id)
🗑

2017-07-04 07:21 UTC, Yajo commented on base_location_nuts/models/res_partner.py
> +            result = {'value': {'country_id': self.state_id.country_id.id}}
`self.country_id = self.state_id.country_id`

2017-07-04 07:21 UTC, Yajo commented on base_location_nuts/models/res_partner.py
> +            return result
Remove lines 117-119, they are redundant. If you edit `self` under an onchange in the new api, you don't need to return a dict with values.

2017-07-04 07:21 UTC, Yajo commented on base_location_nuts/models/res_partner_nuts.py
> +                                inverse_name='parent_id', string='Children')
Add `oldname='children'`

2017-07-04 07:21 UTC, Yajo commented on base_location_nuts/wizard/nuts_import.py
> +                logger.debug(
Wrong indentation here?

2017-07-04 07:21 UTC, Yajo commented on base_location_nuts/wizard/nuts_import_view.xml
> +          parent="sales_team.menu_localisation"
It's sad to have to add the `sales_team` dependency just for putting the menu somewhere. Do you think there's another place where we can put it and skip this big dependency just for that? 🤔 Or maybe we really need this for other reason?

2017-07-05 14:53 UTC, chienandalu commented
@Yajo Thanks for your comments :) I've tried to implement them all.

2017-07-05 15:07 UTC, chienandalu commented on base_location_nuts/wizard/nuts_import_view.xml
> +          parent="sales_team.menu_localisation"
This family of modules fall into that menu historically. It's no really needed at all for anything else. There aren't much options on base views anyway... Ideas are welcomed :smile:

2017-07-05 15:14 UTC, pedrobaeza commented on base_location_nuts/wizard/nuts_import_view.xml
> +          parent="sales_team.menu_localisation"
Well, on base_location there is another menu defined: https://github.com/OCA/partner-contact/blob/10.0/base_location/views/better_zip_view.xml#L61

2017-07-05 16:03 UTC, chienandalu commented on base_location_nuts/wizard/nuts_import_view.xml
> +          parent="sales_team.menu_localisation"
Right, @pedrobaeza , but this module doesn't depend on that one :confused: It only depended on base before...

2017-07-05 16:07 UTC, pedrobaeza commented on base_location_nuts/wizard/nuts_import_view.xml
> +          parent="sales_team.menu_localisation"
Uhm, OK, let's go this way then.

2017-07-06 08:11 UTC, Yajo commented on base_location_nuts/models/res_partner.py
> +        field = self["nuts%d_id" % level]
No, he is using the right thing. Attributes can get anything from the object, while keys can only get fields, so for security this is the recommended system to access fields with variable names, and even more when the variable comes from outside the method.

Please check slide 40 of https://www.odoo.com/es_ES/slides/slide/10-rules-for-safer-code-398

2017-07-06 08:13 UTC, Yajo commented on base_location_nuts/wizard/nuts_import.py
> +                logger.debug('Reading level=%s, id=%s',
The indentation problem I was referring to is that these are 8 spaces instead of the usual 4. (I mean from the line 195 to 196).

2017-07-06 08:13 UTC, yajo approved these changes

2017-07-06 08:16 UTC, Yajo commented
@chienandalu this looks almost perfect now. Could you please fix that little comment and squash all the latest migration-related commits to proceed with merge?

2017-07-06 08:19 UTC, pedrobaeza commented on base_location_nuts/models/res_partner.py
> +        field = self["nuts%d_id" % level]
Well, this system can't be abused like the scenario of the slides. My fear is that this is not a documented way of accessing a field. The official way is with dot notation (and thus, `getattr`), but I see in the slides that is using this method, so go on...

2017-07-06 08:23 UTC, chienandalu commented
@Yajo Fixed and commits squashed

2017-07-06 08:31 UTC, Yajo commented on base_location_nuts/models/res_partner.py
> +        field = self["nuts%d_id" % level]
Well, that presentation was given by @odony, so I guess that makes it somehow officially documented. Maybe a PR to docs would be good.

2017-07-06 09:02 UTC, merged

2017-07-06 14:02 UTC, odony commented on base_location_nuts/models/res_partner.py
> +        field = self["nuts%d_id" % level]
:+1: let's make it more official: odoo/odoo@464fe4a185316cf9af9ae15385bd55662534109b

2017-07-06 14:28 UTC, pedrobaeza commented on base_location_nuts/models/res_partner.py
> +        field = self["nuts%d_id" % level]
Thank your very much for the update on the documentation, Olivier!

2017-07-07 08:11 UTC, Yajo commented on base_location_nuts/models/res_partner.py
> +        field = self["nuts%d_id" % level]
Thanks, great little addition! 👏 👏