[10.0][MIG] partner_second_lastname: Migration to 10.0
OCA/partner-contact pull request #437
Opened 2017-06-22 00:32 UTC by pedrobaeza

Migration commit is dfdc556a5bb5bb297b69deb23faecd1201ca3283

2017-06-22 00:32 UTC, pedrobaeza commented
cc @Tecnativa

2017-06-22 07:32 UTC, yajo approved these changes

2017-06-22 07:32 UTC, Yajo commented on partner_second_lastname/README.rst
> +    * `Antonio Espinosa <mailto:antonioea@antiun.com>`_.
All these credits should be updated.

2017-06-22 07:32 UTC, Yajo commented on partner_second_lastname/models/res_partner.py
> +    @api.multi
It's good to remove the `@api.one` calls, just remember than in v10 `@api.multi` is the same as removing the decorator.

2017-06-22 08:20 UTC, yajo approved these changes
Over-approved now!

2017-06-22 20:18 UTC, lasley requested changes

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/README.rst
> +Contact partners will need to fulfill at least one of the name fields
s/fulfill/fill

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/134/8.0
10.0

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/README.rst
> +<https://github.com/OCA/partner-contact/issues/new?body=module:%20partner_second_lastname%0Aversion:%208.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20beha
old template

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/__manifest__.py
> +        "partner_firstname"
trailing comma

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/models/base_config_settings.py
> +    def _partner_names_order_selection(self):
`api.model`?

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/models/base_config_settings.py
> +    @api.multi
`@api.model`? Or `model_cr_context` maybe? Definitely not `multi`

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/models/res_partner.py
> +    @api.one
Deprecated

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/models/res_partner.py
> +        before, after = dict(), dict()
`efore, after = {}, {}`

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/models/res_partner.py
> +            self.update(before)
`.update`?

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/models/res_partner.py
> +            self.update(after)
`.update`?

2017-06-22 20:18 UTC, lasley commented on partner_second_lastname/models/res_partner.py
> +                    raise error
`error` is superfluous - just `raise` inside of the `except` will do the same thing IIRC

2017-06-22 23:54 UTC, pedrobaeza commented on partner_second_lastname/models/base_config_settings.py
> +    def _partner_names_order_selection(self):
As the overwritten method is by omission `@api.multi`, I let it the same

2017-06-22 23:54 UTC, pedrobaeza commented on partner_second_lastname/models/base_config_settings.py
> +    @api.multi
The same for this: mimicking overwritten method.

2017-06-22 23:55 UTC, pedrobaeza commented on partner_second_lastname/models/res_partner.py
> +    @api.one
I know, but I don't want to change this logic right now (not too much time for this) :wink:

2017-06-22 23:56 UTC, pedrobaeza commented on partner_second_lastname/models/res_partner.py
> +            self.update(before)
Yes, this way you update multiple fields without triggering a write.

2017-06-22 23:56 UTC, pedrobaeza commented on partner_second_lastname/models/res_partner.py
> +            self.update(after)
The same

2017-06-23 00:01 UTC, lasley commented on partner_second_lastname/models/res_partner.py
> +            self.update(before)
Interesting, but when is the write actually triggered?

2017-06-23 00:02 UTC, pedrobaeza commented on partner_second_lastname/models/res_partner.py
> +            self.update(before)
At the end of the inverse computation round

2017-06-23 00:03 UTC, pedrobaeza commented on partner_second_lastname/models/res_partner.py
> +            self.update(before)
This is only when saving. If not, everything is kept in cache.

2017-06-29 02:37 UTC, gustavovalverde commented
Is it safe to use this "as is" before being merged?

2017-06-29 07:51 UTC, pedrobaeza commented
@gustavovalverde Why don't you try and tell me?

2017-06-29 14:53 UTC, lasley approved these changes

2017-06-29 14:53 UTC, lasley commented
@pedrobaeza - squash as your leisure & we can merge

2017-06-29 23:32 UTC, pedrobaeza commented
OK, merging then

2017-06-29 23:33 UTC, merged