Migrate base_partner_merge to V10
OCA/partner-contact pull request #445
Opened 2017-07-05 15:20 UTC by alan196

2017-07-05 15:59 UTC, rousseldenis requested changes

2017-07-05 15:59 UTC, rousseldenis commented on base_partner_merge/base_partner_merge.py
> +from openerp.addons.crm.wizard.base_partner_merge import *  # noqa
@alan196 Since v10, use odoo.* in imports

2017-07-05 15:59 UTC, rousseldenis commented on base_partner_merge/validate_email.py
> +from openerp.addons.crm.wizard.validate_email import *  # noqa
@alan196 Same as above

2017-07-05 15:59 UTC, rousseldenis commented on base_partner_merge/base_partner_merge.py
> +from openerp.addons.crm.wizard.base_partner_merge import *  # noqa
@alan196 Put models in a 'models' directory
See https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#directories

2017-07-05 16:13 UTC, ougc27 approved these changes

2017-07-05 16:20 UTC, alan196 commented
@rousseldenis changes are done.

Thanks for your review 👍

2017-07-05 16:54 UTC, luistriana28 commented
+1

2017-07-06 08:00 UTC, rousseldenis approved these changes
:+1: Code review

2017-07-06 15:57 UTC, moylop260 commented on base_partner_merge/views/base_partner_merge.xml
>      <data>
Remove unused `data`

2017-07-06 16:00 UTC, moylop260 approved these changes
👍 
(Just small change)

2017-07-06 16:07 UTC, alan196 commented
Change DONE Thanks @moylop260 for the review.

2017-07-07 00:38 UTC, merged