10.0 mig partner identification gln mgs
OCA/partner-contact pull request #446
Opened 2017-07-07 10:08 UTC by GillesTephaneMeyomesse

2017-08-23 07:23 UTC, rousseldenis commented
@GillesTephaneMeyomesse Can you check Codecoverage and add test for False values ?

2017-08-23 07:37 UTC, GillesTephaneMeyomesse commented
@rousseldenis Of course I'll inform you at the next commit

2017-08-23 15:54 UTC, GillesTephaneMeyomesse commented
@rousseldenis can you review changes

2017-08-24 07:29 UTC, rousseldenis requested changes
Minor comment. LGTM

2017-08-24 07:29 UTC, rousseldenis commented on partner_identification_gln/README.rst
> +.. repo_id is available in https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt
@GillesTephaneMeyomesse You can remove this line

2017-08-24 08:39 UTC, GillesTephaneMeyomesse commented
@rousseldenis thank's fixed

2017-08-25 14:24 UTC, rousseldenis approved these changes
:+1:

2017-11-07 09:55 UTC, rousseldenis commented
@Cedric-Pigeon

2018-12-04 14:29 UTC, rvalyi commented
superseded by this evil PR https://github.com/OCA/partner-contact/pull/666

2018-12-04 17:38 UTC, closed without merging