[10.0] [ADD] partner_phone_extension
OCA/partner-contact pull request #457
Opened 2017-08-02 12:42 UTC by nikul-serpentcs

Partner Phone Number Extension
===============================

This module adds a phone number extension field in partner form view.

2017-08-02 12:45 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-08-02 13:38 UTC, LoisRForgeFlow approved these changes
Tested on runbot

2017-08-02 13:42 UTC, AaronHForgeFlow approved these changes
LGTM. Checked also on runbot. :+1:

2017-08-02 13:42 UTC, aheficent commented on partner_phone_extension/README.rst
> +
One blank line is enough

2017-08-03 07:14 UTC, AaronHForgeFlow approved these changes

2017-08-03 07:42 UTC, yajo requested changes

2017-08-03 07:42 UTC, Yajo commented on partner_phone_extension/__init__.py
> +#   (<http://www.serpentcs.com>)
Man! So much copyright holders for 1 line of code, isn't it?
🔥 this (see https://github.com/OCA/maintainer-tools/pull/260)

2017-08-03 07:42 UTC, Yajo commented on partner_phone_extension/models/__init__.py
> +#   (<http://www.serpentcs.com>)
🔥

2017-08-03 07:42 UTC, Yajo commented on partner_phone_extension/models/res_partner.py
> +    extension = fields.Char('Extension', help="Phone Number Extension.")
I guess the name should be `phone_extension`, adding `oldname="extension"` to the field definition.

2017-08-03 08:47 UTC, yajo requested changes

2017-08-03 08:47 UTC, Yajo commented on partner_phone_extension/models/res_partner.py
> +    extension = fields.Char('Phone Extension', oldname="extension",
But call the field `phone_extension`

2017-08-03 08:47 UTC, Yajo commented on partner_phone_extension/models/res_partner.py
> -# -*- coding: utf-8 -*-
This precise line you have to keep it, I was talking about the copyright ones.

2017-08-03 13:52 UTC, aheficent commented
Hi @nikul-serpentcs, you forgot to change the field name in the view

2017-08-04 07:30 UTC, aheficent commented on partner_phone_extension/views/res_partner_view.xml
>                  <field name="extension"/>
@nikul-serpentcs Also here please

2017-08-16 09:08 UTC, aheficent commented
@Yajo can you review this again?

2017-08-17 11:14 UTC, lreficent commented
Please, @nikul-serpentcs squash the commits of the migration into just one.

2017-08-18 10:48 UTC, nikul-serpentcs commented
@lreficent squashed the commits

2017-08-21 09:10 UTC, yajo approved these changes

2017-08-21 09:14 UTC, merged