[10.0] partner noncommercial
OCA/partner-contact pull request #477
Opened 2017-09-22 17:03 UTC by NL66278

Migrated module from 8.0.

Module renames commercial names for Sales menu to Partners, and also limits Customers to people actually doing sales, while other users get to choose between Organisations, persons or all partners.

All in all a few simple changes that make the UI more appropiate for non commercial organisations.

2017-10-03 09:03 UTC, gonzaloruzafa approved these changes
+1 Functional Testing Ok.

2017-10-03 13:39 UTC, leemannd approved these changes
Thanks for the port. Only nitpicking.
Agreed once changed

2017-10-03 13:39 UTC, leemannd commented on partner_noncommercial/data/ir_translation.xml
> +<odoo><data>
<data> can be removed

2017-10-03 13:39 UTC, leemannd commented on partner_noncommercial/__manifest__.py
> +# © 2015-2017 Therp BV (http://therp.nl).
s/©/Copyright

2017-10-03 14:18 UTC, NL66278 commented
@leemannd Thanks for your review. Changes have been done.

2017-10-18 10:39 UTC, NL66278 commented
@Yajo If you agree requested changes have been done, could you remove Needs Fixing and Needes Review labels? I am not allowed to edit labels myself.

2017-10-18 10:45 UTC, Yajo commented
I'm afraid you still will have to fight a little bit with git to get this ready to migrate. 😅 

1. Get [all commits from previous versions](https://github.com/OCA/partner-contact/commits/8.0/partner_noncommercial). See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0 for help.
2. Squash all translation-related commits into one.
3. Squash all migration-related commits into one.

Thanks!

2017-10-18 10:45 UTC, yajo requested changes
I'm afraid you still will have to fight a little bit with git to get this ready to migrate. 😅 

1. Get [all commits from previous versions](https://github.com/OCA/partner-contact/commits/8.0/partner_noncommercial). See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0 for help.
2. Squash all translation-related commits into one.
3. Squash all migration-related commits into one.

Thanks!

2017-11-01 15:37 UTC, pedrobaeza commented on partner_noncommercial/README.rst
> +suitable for use in non commercial organisations.
Can you explain a bit more the changes made?

2017-12-16 00:02 UTC, hbrunn commented
@NL66278 please follow up on https://github.com/OCA/partner-contact/pull/477#pullrequestreview-70167217, and add a bit to coverage

2018-10-02 12:01 UTC, hbrunn commented
@Yajo agree to merge?

2018-10-02 12:35 UTC, nikul-serpentcs reviewed
Small Change

2018-10-02 12:35 UTC, nikul-serpentcs commented on partner_noncommercial/__init__.py
> +# © 2016 Therp BV (http://therp.nl).
Remove Copyright from all `__init__` file

2018-10-02 12:35 UTC, nikul-serpentcs commented on partner_noncommercial/__manifest__.py
> +    "author": "Therp BV,Camptocamp,Odoo Community Association (OCA)",
Add Website as per [this](https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L10)

2018-10-02 12:35 UTC, nikul-serpentcs commented on partner_noncommercial_multi_relation/__manifest__.py
> +    "author": "Therp BV,Odoo Community Association (OCA)",
same hare

2018-10-02 17:44 UTC, NL66278 commented
@nikul-serpentcs I added the website keys. kept the copyright in all the init files. We have them everywhere in all modules in all python files. You might debate about the use, but would be inconsistent to just change it here.

2018-10-03 04:58 UTC, nikul-serpentcs commented
@NL66278 Here we followed OCA terms and in [here](https://github.com/OCA/maintainer-tools/blob/master/template/module/models/__init__.py)

2018-10-03 06:56 UTC, NL66278 commented
@nikul-serpentcs OK, I changed it. Thanx for the links.

2018-10-03 14:46 UTC, yajo approved these changes
Please, could you squash the migration commits, to merge? Thanks!

2018-10-03 15:06 UTC, NL66278 commented
@Yajo commits have been squashed.

2018-10-03 15:18 UTC, Yajo commented
Yikes, sorry to ask for this for the 3rd time in the thread, but I think you didn't understand me: Only the *migration* commits.

The process is:

1. Get all commits from the previous branch (you can squash translation commits if you want).
1. Put 1 more commit (squashed) with the migration for this branch.

2018-10-03 18:58 UTC, NL66278 commented
@Yajo I might have misunderstood your remark on squashing. Anyway I now recreated the commits with the 8.0 history in them. As 8.0 was a migration of 7.0 without the history, that was as far as I could get. Hope it is OK now. Thanks for your patience.

2018-10-04 05:54 UTC, Yajo commented
Thanks! It seems you still need to fix https://travis-ci.org/OCA/partner-contact/jobs/436795018#L623. Squash the fix with your last commit and tell me, to merge.

2018-10-04 06:32 UTC, NL66278 commented
@Yajo Fixed!

2018-10-04 06:35 UTC, bodedra approved these changes

2018-10-04 09:12 UTC, merged