[11.0] [MIG] partner_firstname: Migration to 11.0
OCA/partner-contact pull request #487
Opened 2017-10-09 10:08 UTC by etobella

Migration to 11.0

2017-10-09 14:54 UTC, JordiBForgeFlow requested changes

2017-10-09 14:54 UTC, jbeficent commented on partner_firstname/models/base_config_settings.py
>          self.partner_names_order_changed = self._compute_names_order_changed()
This assignment already occurs in method `_compute_names_order_changed`. As a consequence, it is failing to hide the button "Recalculate names". If you just call to `self._compute_names_order_changed()` it works.

2017-10-09 14:54 UTC, jbeficent commented on partner_firstname/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/134/11.0
Change the readme also, from:

> You can configure some common name patterns for the inverse function
in Settings > Configuration > General settings

To:
> You can configure some common name patterns for the inverse function
in Settings > General settings

2017-10-09 15:07 UTC, rgarnau reviewed
LGTM :+1:

2017-10-09 15:08 UTC, rgarnau approved these changes

2017-10-09 16:43 UTC, JordiBForgeFlow approved these changes
:+1: Technical and functional review

2017-10-10 07:30 UTC, pedrobaeza commented
Please squash together "OCA Transbot..." commits.

2017-10-10 08:27 UTC, Yajo commented
Runbot is red, could you check that too please?

2017-10-10 10:32 UTC, hveficent commented
LGTM :+1:

2017-10-10 10:34 UTC, HviorForgeFlow approved these changes

2017-10-11 10:23 UTC, etobella commented
@Yajo runbot is green now.

2017-10-27 12:49 UTC, njeudy reviewed
- Code check and real tests: Ok for me

2017-10-27 12:52 UTC, njeudy approved these changes
Code check and real tests: Ok for me

2017-10-27 15:02 UTC, merged

2018-06-10 07:06 UTC, cliffkujala commented
Not specifically a v11.0 problem, but the README file for partner_firstname links to non HTTPS images so it throws a mixed content warning when viewing the App in the backend.  Problem starts at line 108.

Should be:
`.. image:: https://odoo-community.org/logo.png
   :alt: Odoo Community Association
   :target: https://odoo-community.org

This module is maintained by the OCA.

OCA, or the Odoo Community Association, is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

To contribute to this module, please visit https://odoo-community.org.`

But it is all http:// below line 108.

2018-06-11 17:46 UTC, pedrobaeza commented
@cliffkujala Fixed.