[ADD] Module which allow to deactivate partner bank accounts
OCA/partner-contact pull request #489
Opened 2017-10-10 13:58 UTC by benwillig

2017-10-10 14:06 UTC, pedrobaeza approved these changes

2017-10-10 14:41 UTC, sbidoul approved these changes

2017-10-11 08:05 UTC, yajo requested changes

2017-10-11 08:05 UTC, Yajo commented on partner_bank_active/README.rst
> +Just install it.
Drop installation section then.

2017-10-11 08:05 UTC, Yajo commented on partner_bank_active/README.rst
> +No configuration needed.
Drop configuration section then.

2017-10-11 08:05 UTC, Yajo commented on partner_bank_active/README.rst
> +. Set it as active/inactive
Use `#.` at the start of lines to get autonumbered lists.

2017-10-11 08:05 UTC, Yajo commented on partner_bank_active/__manifest__.py
> +        Allow to deactivate a partner bank account""",
Single line please

2017-10-11 08:05 UTC, Yajo commented on partner_bank_active/__manifest__.py
> +    'website': 'https://github.com/OCA/account-financial-tools',
Either PR is in the wrong place, or this line is wrong.

2017-10-13 13:50 UTC, benwillig commented
@Yajo Updated this PR based on your review.

2017-12-13 18:53 UTC, benwillig commented
Can you update your review @Yajo ? Thanks

2017-12-14 08:52 UTC, yajo approved these changes

2017-12-14 08:52 UTC, merged