11.0 migrated base_partner_sequence
OCA/partner-contact pull request #531
Opened 2017-12-13 17:50 UTC by jesusVMayor

2017-12-18 09:47 UTC, simoneversienti commented on base_partner_sequence/models/partner.py
> +
Why is there this empty line?

2018-01-03 06:09 UTC, FrancoTampieri requested changes

2018-01-03 06:09 UTC, drdran commented on base_partner_sequence/models/partner.py
> +        :param cr: database cursor
Hi, remove from the comments the old reference to cr, uid, id if not used in the code

2018-01-03 06:09 UTC, drdran commented on base_partner_sequence/models/partner.py
> +        :param uid: current user id
Hi, remove from the comments the old reference to cr, uid, id if not used in the code

2018-01-03 06:09 UTC, drdran commented on base_partner_sequence/models/partner.py
> +        :param id: id of the partner object
Hi, remove from the comments the old reference to cr, uid, id if not used in the code

2018-01-03 06:11 UTC, drdran commented
@jesusVMayor I fixed the problem on the main repository, so you can rebase and apply the simply mods that I found in you PR.

Regards

Franco

2018-01-08 10:57 UTC, jesusVMayor commented
fixed

2018-02-05 10:11 UTC, yajo approved these changes
Code review

2018-02-27 14:30 UTC, ddufresne commented
:+1: code + functionnal

2018-02-28 00:47 UTC, merged