11.0 mig base partner merge
OCA/partner-contact pull request #545
Opened 2018-01-09 12:43 UTC by JayVora-SerpentCS

Module Migrated to 11.0

2018-04-17 12:09 UTC, tschanzt requested changes
Only minor stuff:
  - The utf-8 header isn't needed anymore for python3. 
  - Remove the .pot file, since they aren't stored in the module anymore.

Otherwise i tested it and it works. :+1:

2018-04-17 12:29 UTC, yvaucher approved these changes
Appart from @tschanzt remarks, LGTM

2018-04-18 06:24 UTC, simahawk requested changes

2018-04-18 06:24 UTC, simahawk commented on base_partner_merge/README.rst
> +Yannick Vaucher
add email `<yannick.vaucher@camptocamp.com>` and "Do not contact contributors directly about support or help with technical issues." see https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-04-18 06:24 UTC, simahawk commented on base_partner_merge/__init__.py
> +# -*- coding: utf-8 -*-
remove coding headers

2018-04-18 06:24 UTC, simahawk commented on base_partner_merge/__manifest__.py
> +    'license': 'AGPL-3',
add `'website': 'https://github.com/OCA/partner-contact',`

2018-04-18 06:24 UTC, simahawk commented on base_partner_merge/views/base_partner_merge.xml
> +    <record model='ir.ui.view' id='base_partner_merge_automatic_wizard_form'>
pls do not mixup quotes: use double quotes all around

2018-04-18 06:24 UTC, simahawk commented on base_partner_merge/views/base_partner_merge.xml
> +                    <p class="oe_grey" attrs="{'invisible': [('state', '!=', ('option'))]}">
do not wrap `option` w/ parenthesis: `[('state', '!=', 'option')]`

2018-04-18 06:24 UTC, simahawk commented on base_partner_merge/views/base_partner_merge.xml
> +                    <group attrs="{'invisible': [('state', '!=', 'finished')]}" col="1">
add a name to this group

2018-04-18 06:24 UTC, simahawk commented on base_partner_merge/views/base_partner_merge.xml
> +                    <group attrs="{'invisible': ['|', ('state', 'not in', ('selection', 'finished')), ('number_group', '=', 0)]}">
same here and all the other groups

2018-04-18 06:24 UTC, simahawk commented on base_partner_merge/wizard/base_partner_merge.py
> +from odoo.addons.crm.wizard.base_partner_merge import *  # noqa
seems we import only 2 things: `MergePartnerLine` and `MergePartnerAutomatic` -> remove the wildcard

2018-05-28 08:48 UTC, simahawk commented
@JayVora-SerpentCS  ping :)

2018-05-28 09:48 UTC, JayVora-SerpentCS commented
checking

2018-06-08 03:14 UTC, huyly0909 approved these changes

2018-06-28 14:55 UTC, yvaucher commented
LGTM, I'll merge and squash the last commits in one.

2018-06-28 15:00 UTC, yvaucher commented
Merged at https://github.com/OCA/partner-contact/commit/66d236fe99425b4e0ccdbb398ec7aac21fbea159

2018-06-28 15:00 UTC, closed without merging

2018-06-28 15:01 UTC, yvaucher commented
Thank you @JayVora-SerpentCS