[10.0] partner_changeset - Fix condition on test_enable
OCA/partner-contact pull request #563
Opened 2018-02-21 15:40 UTC by yvaucher

Context key `test_enable` will always be empty.

Thus previous patch had no effect.
Still this might speed the tests of other modules as we will only trigger changeset methods in thoses tests.

2018-02-21 15:41 UTC, yvaucher commented
See other example here:

https://github.com/OCA/account-invoicing/blob/10.0/sale_timesheet_invoice_description/models/sale.py#L59

2018-02-23 08:33 UTC, yajo approved these changes

2018-02-23 08:38 UTC, pedrobaeza commented
Why Travis is red?

2018-02-23 19:33 UTC, yvaucher commented
@pedrobaeza no idea the fixed condition seems right to me now.

By pass change set if:
Specificaly using __no_changeset
or
we are testing a module which is not this one.

Or maybe we are missing some definition of the context `test_partner_changeset`

2018-03-07 10:34 UTC, acsonefho approved these changes

2019-03-20 21:22 UTC, grindtildeath approved these changes
I approve although travis is red because `self.env.context.get('test_enable')` doesn't make much sense.

2019-03-25 08:57 UTC, yajo requested changes
This PR breaks the branch.

2020-02-18 13:54 UTC, NL66278 commented
@yvaucher Do you still intend to fix this branch?

2020-02-19 19:40 UTC, yvaucher commented
@NL66278 thx for the reminder I'll have to dive into that again. It has been a while.

2020-04-28 18:09 UTC, NL66278 commented
Any update on this? Travis errors are in the tests for this module...

2020-05-15 20:56 UTC, yvaucher commented
@NL66278 finally fixed it, it was stupidly missing the use of the context key in the tests.

Should be green now.

2020-05-18 08:00 UTC, yajo approved these changes

2020-05-18 09:28 UTC, yvaucher commented
/ocabot merge patch

2020-05-20 14:40 UTC, pedrobaeza commented
There has been a problem with merge bot, but it's fixed now, so you can relaunch.

2020-06-08 12:42 UTC, yvaucher commented
/ocabot merge patch

2020-06-08 13:07 UTC, merged