[8.0][MIG] Backport of partner_coc
OCA/partner-contact pull request #605
Opened 2018-07-09 14:18 UTC by pankk

Backport of the 10.0 module partner_coc.

2018-07-11 14:53 UTC, tarteo requested changes
I get an error:
`AttributeError: 'res.partner' object has no attribute '_compute_identification'` 
I think the method _compute_identification is not available in 8.0. I think you have to manually create res.partner.id_number

2018-07-12 08:43 UTC, pankk commented
@tarteo Thanks for testing! I mixed up two versions of partner_identification. The one on the 8.0 branch in this repo is a backport of 9.0. I was using a version that was backported from the 10.0 version. So I should test if the 10.0 backport doesn't break compatibility with anything that depends on it (i.e. partner_identification_gln) if we want to use that version. I also need to confirm who did the backport so they can be credited before I (or they) make a PR for it.

2018-08-22 13:57 UTC, pankk commented
I've since added #612 to solve the issue @tarteo reported above.

2019-09-02 00:04 UTC, rafaelbn commented
===========
Partner CoC
===========

Adds a field 'Chamber Of Commerce Registration Number' to partner.

2020-02-20 13:37 UTC, thomaspaulb commented
@rafaelbn I dont see that missing `=` anymore; time for an updated review from your side?

2020-02-20 13:39 UTC, thomaspaulb approved these changes
PyLint and Travis errors are unrelated.

2020-02-20 13:53 UTC, NL66278 approved these changes
:+1: LGTM

2020-02-20 21:26 UTC, rafaelbn commented
/ocabot merge

2020-02-20 21:26 UTC, rafaelbn approved these changes
:+1:

2020-04-29 09:48 UTC, NL66278 commented on partner_coc/__openerp__.py
> +    'website': 'http://www.onestein.eu',
Change to https://github.com/OCA/partner-contact

2020-04-29 09:48 UTC, NL66278 commented on partner_coc/__manifest__.py
> +{
Delete this file

2020-04-29 09:50 UTC, NL66278 requested changes
Needs a few changes. See other comments.

2020-07-06 18:18 UTC, NL66278 approved these changes
:+1: LGTM

2020-09-25 08:39 UTC, NL66278 commented
/ocabot merge nobump

2020-09-25 11:02 UTC, merged