[11.0][partner_nav_to_contacts] Allow browsing from the contact form view (companies) to its contacts.
OCA/partner-contact pull request #649
Opened 2018-11-02 09:17 UTC by Dajuayen

To navigate from a customer or supplier to its contacts,
the name of the contact in the kanban card of each contact
in the contacts and addresses tab in the form view of the source contact is a link
that when clicked on it, shows us the information of the selected contact.

To return to the form with the data of the source contact, you just have to retrace the path of the bread crumbs.

2018-11-02 11:22 UTC, pedrobaeza commented
The module name shouldn't contain plurals. I would go for `partner_children_navigation`.

2018-11-02 11:40 UTC, Dajuayen commented
> The module name shouldn't contain plurals. I would go for `partner_children_navigation`.

'children' is a word with a plural meaning.
Is it okay for you to rename the module as 'partner_child_navigation'?

2018-11-02 11:46 UTC, pedrobaeza commented
@Dajuayen the problem is not with words that implies plural (like `children` or `people`). The specific problem is with `s` for making a plural. It happens that you misspell continuously module names due to these `s`. For example, previously the module `partner_multi_relation` was named `partner_relations`. Do you see the change I want to express? Check also out contributing section about that: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#id6

2018-11-02 11:58 UTC, Dajuayen commented
@pedrobaeza thanks for the explanation. I have already renamed the module and the pull request.

2018-11-03 13:19 UTC, pedrobaeza commented
@Dajuayen look how I rename the PR title for adjusting it to guidelines.

2018-11-03 21:42 UTC, Dajuayen commented
@pedrobaeza I think everything is ok.

2018-11-03 23:20 UTC, pedrobaeza commented
Why do you rename again the title? I have put it the proper way.

2018-11-04 10:47 UTC, Dajuayen commented
Sorry @pedrobaeza , I did not understand your message well. I thought you were asking me to change the title of the PR to finish approving it.

On the other hand, everything is OK, isn't it?

2018-11-05 09:10 UTC, pedrobaeza commented
@Dajuayen I have only made a review on the PR guidelines, not the content itself.

2020-09-25 11:21 UTC, NL66278 commented on partner_children_navigation/__manifest__.py
> +# © 2018 David Juaneda <djuaneda@sdi.es>
Use the word Copyright here, not the symbol.

2020-09-25 11:22 UTC, NL66278 commented on partner_children_navigation/__manifest__.py
> +# SDI
Delete this line

2020-09-25 11:22 UTC, NL66278 commented on partner_children_navigation/__manifest__.py
> +    'website': 'https://github.com/OCA/social',
website should be .../partner-contact

2020-09-25 11:23 UTC, NL66278 commented on partner_children_navigation/__manifest__.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
Make it https:

2020-09-25 11:24 UTC, NL66278 commented on partner_children_navigation/models/res_partner.py
> +# SDI
Delete first line, use Copyright word, https: url....

2020-09-25 11:25 UTC, pedrobaeza commented
Isn't this the same as https://odoo-community.org/shop/product/partner-contact-access-link-5422 ?

2020-09-25 11:25 UTC, NL66278 commented on partner_children_navigation/tests/__init__.py
> +from . import test_res_partner
Make sure there is the newline.

2020-09-25 11:25 UTC, NL66278 commented on partner_children_navigation/tests/test_res_partner.py
> +# SDi
See comments on manifest and model file...

2020-09-25 11:28 UTC, NL66278 requested changes
Thank you for your contribution!

Please take up the comments given.

And black your python code, this will minimize changes when upgrading to future releases. Blacked code will be required for Odoo >= 13.0.

2020-09-25 11:29 UTC, pedrobaeza commented
@NL66278 please see https://github.com/OCA/partner-contact/pull/649#issuecomment-698876179

2020-09-25 11:35 UTC, NL66278 commented
@pedrobaeza It looks the same. So shall I close this? If functionality needed on 11.0, the 12.0 module should be backported I think...

2020-09-25 11:37 UTC, pedrobaeza commented
Yes, I think so.

2020-09-25 12:03 UTC, NL66278 commented
This module provides the same functionality as partner_contact_access_link in 12.0 and 13.0. So, if the functionality is also needed on 11.0, backport that module.

2020-09-25 12:03 UTC, closed without merging