[12.0][MIG] Base Partner Sequence
OCA/partner-contact pull request #668
Opened 2018-12-10 17:13 UTC by qgroulard

Migration of base_partner_sequence to 12.0

2018-12-11 08:48 UTC, gva-acsone approved these changes
👍

2018-12-11 08:51 UTC, rousseldenis commented on base_partner_sequence/__manifest__.py
>      "category": "Generic Modules/Base",
@qgroulard Maybe adding development_status https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L9

2018-12-11 08:51 UTC, rousseldenis approved these changes

2018-12-11 11:26 UTC, qgroulard commented on base_partner_sequence/__manifest__.py
>      "category": "Generic Modules/Base",
Done.

2018-12-13 06:19 UTC, nikul-serpentcs requested changes
Minor Change

2018-12-13 06:19 UTC, nikul-serpentcs commented on base_partner_sequence/tests/test_base_partner_sequence.py
> +import openerp.tests.common as common
odoo

2018-12-13 09:08 UTC, qgroulard commented on base_partner_sequence/tests/test_base_partner_sequence.py
> +import openerp.tests.common as common
Fixed

2018-12-13 10:02 UTC, nikul-serpentcs approved these changes
Code Review LGTM :+1:

2018-12-15 18:02 UTC, merged