10 partner history
OCA/partner-contact pull request #669
Opened 2018-12-11 09:33 UTC by bguillot

Hi

This module sets versions on partners.
A versionned partner can't be modify.

It is a solution to the issue : https://github.com/OCA/partner-contact/issues/404

2018-12-11 10:04 UTC, rousseldenis requested changes
@bguillot Could you maybe use https://github.com/OCA/maintainer-tools#readme-generator ? And complete manifest entry keys https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L9

But I like the approach. Maybe you could add a little bit more explanation on how it works.

2018-12-11 10:04 UTC, rousseldenis commented on partner_address_version/__manifest__.py
> +    'data': [
Please remove blank entry

2018-12-11 10:05 UTC, rvalyi commented
I don't have an opinion on it yet, but here is some unofficial feedback from the rebellion https://twitter.com/cedrickrier/status/1072428174582136832

2018-12-12 15:08 UTC, yvaucher approved these changes
LGTM, would help to document it a bit better, plus I added a performance suggestion on check of versionned fields.

2018-12-12 15:08 UTC, yvaucher commented on partner_address_version/models/res_partner.py
> +        )
As you don't need the list of field put in written_versioned_fields. You could use a more efficient way by using `any`

```python
has_written_versioned_fields = any(
    (k in version_fields) for k in vals.keys()
)
```

Make sur that you use a generator (not using `[]` of comprehension list), it will be faster as it will exit the loop early.

2018-12-12 15:08 UTC, yvaucher commented on partner_address_version/readme/DESCRIPTION.rst
> +This module allows to manage versions for partner addresses.
Can you write a sentence about the behavior when writting on a field that is versionned?

And maybe also why versionning is useful, for instance for e-commerce to track history.

2018-12-12 15:08 UTC, yvaucher commented on partner_address_version/tests/test_address_version.py
> +class TestAddressVersion(TransactionCase):
You can use a SavepointCase here to create the partner only once.

2018-12-12 15:27 UTC, yvaucher requested changes

2018-12-12 15:27 UTC, yvaucher commented on partner_address_version/models/res_partner.py
> +        versioned_partner = self.with_context(active_test=False).search(
What happens if there are multiple hits? Let's say 2 customers living together but for convenience make their delivery go to the work place of one. You would have the exact same hash but for 2 customers. You certainly want to have 1 shipping address even if the exact same on each customer, that way relation to parent_id is still correct.

2018-12-12 17:03 UTC, bguillot commented
Thank you @yvaucher !

I did the changes !

2018-12-13 04:46 UTC, nikul-serpentcs requested changes
Minor Change

2018-12-13 04:46 UTC, nikul-serpentcs commented on partner_address_version/__manifest__.py
> +    'website': 'http://www.akretion.com',
@bguillot Replace URL as per [this](https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L11)

2019-05-28 09:22 UTC, rousseldenis commented
@bguillot Could you check travis ?

2019-05-28 13:55 UTC, bguillot commented
@rousseldenis I fixed the issue, travis is green now !

2019-05-28 14:08 UTC, rousseldenis commented on partner_address_version/models/res_partner.py
> +        versioned_partner = self.with_context(active_test=False).search(
@bguillot

2019-05-28 14:30 UTC, bguillot commented on partner_address_version/models/res_partner.py
> +        versioned_partner = self.with_context(active_test=False).search(
I added the parent_id in the version fields to handle this case.
 Yannick was with me at that time so we discussed it directly.

2019-05-28 14:32 UTC, bguillot commented on partner_address_version/models/res_partner.py
> +        versioned_partner = self.with_context(active_test=False).search(
I added the "parent_id" field in the version fields to handle this case.

2019-05-28 14:33 UTC, rousseldenis approved these changes
Code review

2019-05-28 15:13 UTC, bguillot commented
@yvaucher Is your request of changes satified ?

2019-05-28 15:13 UTC, bguillot commented
thanks @rousseldenis

2019-05-29 04:39 UTC, nikul-serpentcs commented
@bguillot Squash Commits

2019-05-29 10:33 UTC, bguillot commented
@nikul-serpentcs Squash done

2019-05-29 12:22 UTC, nikul-serpentcs approved these changes
only Code Review LGTM :+1:

2019-06-11 13:51 UTC, merged