[12.0] partner_legal_name: Partner Legal Name module
OCA/partner-contact pull request #677
Opened 2018-12-26 05:15 UTC by rockmanx2010

_ Add a legal_name field
_Show legal_name into res_partner form and treeview

2018-12-26 06:31 UTC, elicoidal reviewed
Thanks for the contribution!

I am not sure though of the functional interest of the module.
For me the legal name should always be in the field `name`.
Adding another field means that you need to potentially change a lot of places.

Is there some specific case where this module should apply (`name` could not contain the legal name for example)?

:-1:

2019-09-20 04:05 UTC, DucTruongKomit commented
@elicoidal  We created this field, because some company(for example in my country), they don't like to use the real name on the report because it's too long, so this field can solve that problem!

2020-10-15 14:41 UTC, NL66278 commented on partner_legal_name/model/base/res_partner.py
> +        partner = self
This is just creating confusion... No need for a different variable.

2020-10-15 14:43 UTC, NL66278 commented on partner_legal_name/model/base/res_partner.py
> +            partner.display_name = partner.legal_name
Why should the legal name be the display name?

2020-10-15 14:46 UTC, NL66278 requested changes
This module seems to replace the actual name consistently with the legal name. Instead of having the legal name as an extra attribute for specific purposes. This IMHO should not be done like this.

2020-12-04 08:39 UTC, NL66278 commented
No reaction to comments.

2020-12-04 08:39 UTC, closed without merging