[12.0] [MIG] partner_address_street3
OCA/partner-contact pull request #690
Opened 2019-01-21 14:23 UTC by hveficent

Standard migration

2019-01-21 15:43 UTC, Nikul-Chaudhary requested changes
Improve Code

2019-01-21 15:43 UTC, Nikul-Chaudhary commented on partner_address_street3/__manifest__.py
> +    'website': 'http://www.camptocamp.com',
@hveficent URL should be https://github.com/OCA/partner-contact

2019-01-21 15:43 UTC, Nikul-Chaudhary commented on partner_address_street3/tests/test_street_3.py
> +        homer = self.env['res.partner'].create({
@hveficent `self.env['res.partner']` use multipal time, So use like global variable

2019-01-22 12:44 UTC, hveficent commented on partner_address_street3/tests/test_street_3.py
> +        homer = self.env['res.partner'].create({
There are only 2 matches. Avoiding nitpicking...

2019-01-24 07:26 UTC, jcdrubay approved these changes

2019-02-08 13:21 UTC, tbaden approved these changes

2019-02-08 13:48 UTC, hveficent commented
@Nikul-Chaudhary update review

2019-02-11 03:55 UTC, Nikul-Chaudhary approved these changes
Code Review LGTM :+1:

2019-02-16 07:36 UTC, merged