[12.0] [MIG] partner_second_lastname
OCA/partner-contact pull request #696
Opened 2019-01-21 18:15 UTC by Nikul-Chaudhary

Partner second lastname
=======================

This module was written to extend the functionality of ``partner_firstname`` to support having a second lastname for contact partners.

In some countries, it's important to have a second last name for contacts.

Contact partners will need to fill at least one of the name fields (*First name*, *First last name* or *Second last name*).

2019-02-06 18:52 UTC, Nikul-Chaudhary commented
@pedrobaeza Could you please review it?

2019-02-13 15:42 UTC, tarteo requested changes

2019-02-13 15:42 UTC, tarteo commented on partner_second_lastname/tests/test_onchange.py
> +# © 2015 Grupo ESOC Ingeniería de Servicios, S.L.U.
© > Copyright

2019-02-13 15:42 UTC, tarteo commented on partner_second_lastname/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Use the split readme.

2019-02-13 15:42 UTC, tarteo commented on partner_second_lastname/models/res_partner.py
> +        oldname="lastname_second"
oldname is not needed

2019-02-14 12:28 UTC, LoisRForgeFlow reviewed
Please, squash transifex commits.

2019-02-25 17:03 UTC, Nikul-Chaudhary commented
@lreficent @tarteo Done

2019-03-01 12:07 UTC, tarteo approved these changes
Thanks.

2019-03-18 13:35 UTC, MiquelRForgeFlow approved these changes
LGTM

2019-03-18 13:37 UTC, merged