[9.0][MIG] migrate module portal_partner_select_all
OCA/partner-contact pull request #715
Opened 2019-03-13 09:35 UTC by robinkeunen

2019-09-01 23:54 UTC, rafaelbn approved these changes

2019-11-21 12:03 UTC, NL66278 commented on portal_partner_select_all/wizard/__init__.py
> +from . import portal_wizard
Still need a coding line in 9.0

2019-11-21 12:04 UTC, NL66278 commented on portal_partner_select_all/wizard/portal_wizard.py
> +# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
Make license lines https:

2019-11-21 12:12 UTC, NL66278 requested changes
:+1: Mostly good, few changes would make it perfect

2019-11-21 12:34 UTC, chienandalu requested changes
Looks fine overall. Please attend comments regarding the shebang remove and my remarks about authorship. Squash your commits when the final change are done.

2019-11-21 12:34 UTC, chienandalu commented on portal_partner_select_all/__openerp__.py
> +              'Coop IT Easy,'
Sorry, but this kind of simple migrations, as welcome as they ar, can't entitle your work as author.

2019-11-21 12:34 UTC, chienandalu commented on portal_partner_select_all/__openerp__.py
> +# Copyright 2019 Coop IT Easy SCRL fs - Robin keunen
The same here. No relevant changes were made to add your copyright

2019-11-21 12:52 UTC, robinkeunen commented
cf #812, the repository this PR used was deleted.

2019-11-21 12:52 UTC, closed without merging