[13.0][ADD] Add partner_sale_address module.
OCA/partner-contact pull request #878
Opened 2020-04-03 06:58 UTC by acsonefho

Module used to restrict invoice/shipping addresses available on the sale order depending on the picked customer. Addresses available are contacts of the customer (or itself).

As the impact is only visual, no unit test needed.

Please tell me if I add this module into the correct repo.

Thanks for reviewers :)

2020-04-03 07:38 UTC, acsonefho commented
Build failed but no errors related to this module.
`13.0` is already red.

2020-04-03 08:22 UTC, ThomasBinsfeld requested changes

2020-04-03 08:22 UTC, ThomasBinsfeld commented on partner_sale_address/models/sale_order.py
> +        domain="['|', ('parent_id', '=', partner_id), ('id', '=', partner_id)]",
```suggestion
        domain="[('id', 'child_of', partner_id)]",
```

2020-04-03 08:22 UTC, ThomasBinsfeld commented on partner_sale_address/models/sale_order.py
> +        domain="['|', ('parent_id', '=', partner_id), ('id', '=', partner_id)]",
```suggestion
        domain="[('id', 'child_of', partner_id)]",
```

2020-04-03 08:22 UTC, ThomasBinsfeld commented on partner_sale_address/readme/DESCRIPTION.rst
> +This module restrict invoice and shipping addresses visible on the sale order depending on
```suggestion
This module restricts invoice and shipping addresses visible on the sale order depending on
```

2020-04-03 08:22 UTC, ThomasBinsfeld commented on partner_sale_address/__manifest__.py
> +    "version": "13.0.1.0.0",
```suggestion
    "version": "13.0.1.0.0",
    "development_status": "Beta",
```

2020-04-03 08:25 UTC, ThomasBinsfeld commented
I think this should be in sale-workflow, don't you?

2020-04-03 08:35 UTC, acsonefho commented
> I think this should be in sale-workflow, don't you?

I put this module here because I think it's more about the contact part than the workflow. It doesn't block or update anything about the workflow.

2020-04-03 08:43 UTC, ThomasBinsfeld approved these changes

2020-04-06 12:14 UTC, chrisdec approved these changes
Functional test

2021-03-03 15:16 UTC, dreispt commented
Tests are failing. Restarted the build just in case.

2021-04-29 13:29 UTC, NL66278 commented on partner_sale_address/__init__.py
> +# Copyright (C) 2020-Today: Odoo Community Association (OCA)
There should be no copyright lines in init files and all license lines (in all files) should be https:

2021-04-29 13:30 UTC, NL66278 commented on partner_sale_address/__manifest__.py
> +# Copyright (C) 2020-Today: Odoo Community Association (OCA)
And do not put -Today in the copyright line. The last year, should be the year that the latest changes were made.

2021-04-29 13:32 UTC, NL66278 requested changes
:+1: Nice addition, but needs some changes to comply with conventions.

2021-10-28 17:29 UTC, NL66278 commented
Questions and remarks not taken up

2021-10-28 17:29 UTC, closed without merging