[MIG] portal_partner_select_all
OCA/partner-contact pull request #889
Opened 2020-04-20 12:05 UTC by mclaeysb

Reverse migrated from v12.

2020-04-20 12:07 UTC, mclaeysb commented
See also https://github.com/OCA/partner-contact/pull/744

2020-04-21 10:42 UTC, mclaeysb commented
@chienandalu I have difficulties understanding the codecov checks. Could you help me?

2020-04-21 13:18 UTC, chienandalu approved these changes
Hi @mclaeysb Thanks for your PR :) I tested it and it's ok

codecov/patch stands for code inside this PR not covered by tests. You can enter into the details and click on the diff tab to see what that code is.
codecov/project stands for the increment (or decrement) of uncovered code added to the repository.

It's highly recommended to add tests to modules to avoid regressions.

2020-05-02 20:24 UTC, skeller1 requested changes
missing tests

code at all: :+1:  LGTM

Tested it on runbot (after assigning the missing user rights the action was available in UI) :+1:

2020-05-02 20:24 UTC, skeller1 commented on portal_partner_select_all/readme/DESCRIPTION.rst
> +When a user wants invite a lot of custumers to the portal it can be a pain to
typo: `custumers` => `customers`

2020-05-04 07:34 UTC, mclaeysb commented on portal_partner_select_all/readme/DESCRIPTION.rst
> +When a user wants invite a lot of custumers to the portal it can be a pain to
Typo fixed. The original code had no tests. Will this be merged without?

2020-05-04 07:44 UTC, skeller1 commented on portal_partner_select_all/readme/DESCRIPTION.rst
> +When a user wants invite a lot of custumers to the portal it can be a pain to
12.0 has no tests, so maybe it should be merged too. Thank you for contributing.

2020-05-04 07:44 UTC, skeller1 approved these changes

2020-05-04 08:06 UTC, skeller1 requested changes
You have to regenerate the docs (to get new README, new static/description index.html) with changed typo

2020-05-04 09:19 UTC, mclaeysb commented
Here we go! Hope this can indeed be merged :)

2020-05-04 09:41 UTC, skeller1 approved these changes

2020-07-17 15:13 UTC, rafaelbn approved these changes

2020-07-17 15:13 UTC, rafaelbn commented
/ocabot merge nobump

2020-07-17 17:56 UTC, merged