[IMP] partner_multi_relation: unlinking partner relations
OCA/partner-contact pull request #896
Opened 2020-04-28 10:35 UTC by skeller1

**Description of the issue/feature this PR addresses:**

Allow unlinking of partner relation recordsets containing records with same res_id

**Current behavior before PR:**

1. Go to Contacts => Relations => Relations
2. Filter for Partner `Bart` (2 records)
3. Select both records in tree view (global checkbox)
4. Delete records
5. Error appears 

![partner_relation_remove_relations](https://user-images.githubusercontent.com/226753/80477657-9e9f9600-894c-11ea-95df-b012badf681e.png)

**Desired behavior after PR is merged:**

- unlink all checked partner relations in tree view without any error

2020-04-28 11:53 UTC, NL66278 requested changes
Hi, while this change will work in this particular module, we also have custom extention modules that show for instance the relation between partner and contact as a relation between two partners. So in that case the underlying model is not res.partner.relation.

See here, if you are interested: https://github.com/NL66278/partner-contact/tree/10.0-partner_multi_relation_parent-turbo/partner_multi_relation_parent


I think the most safe and compatible way to prevent the error would be to keep a dictionary in the unlink method of base resources already seen/unlinked, and skip the unlink of the base-resource if it has already been handled.

2020-04-29 09:13 UTC, skeller1 commented
@NL66278: Thank you for improving my understanding of this addon and the relation.

I started to implement it and I struggled with Cache Miss Error.
Finally I solved the problem using the rec.id field to extract the res_id.
The id of res.partner.relation.all records is build based on the res_id (see screenshot below, line 2 and 13 of the VIEW definition):
![UNION_RELATION](https://user-images.githubusercontent.com/226753/80579224-f3edad00-8a09-11ea-8879-26a4e07aac71.png)

At the end ugly code but the tests are green. :-D.

2020-04-29 09:42 UTC, NL66278 approved these changes
:+1: Nice solution!

2020-04-29 13:50 UTC, skeller1 commented
@NL66278

Could this implementation be failure-prone if the `key_offset` (defined [here](https://github.com/OCA/partner-contact/blob/61ab3fc59a405b2ab90a200fb46465d3a0975be1/partner_multi_relation/models/res_partner_relation_all.py#L20)) has more than 1 digit. Is this possible through other extension addons ....
Still need to learn .....

Thank you

2020-04-29 15:34 UTC, NL66278 approved these changes
:+1: Probably the most foolproof method to solve the problem.

2020-04-29 15:48 UTC, skeller1 commented
> +1 Probably the most foolproof method to solve the problem.

Readable and easy to understand. A long brain evolution by my side. Thank you for your support

2020-04-30 09:55 UTC, rousseldenis approved these changes
Nice!

2020-05-12 16:42 UTC, NL66278 commented
/ocabot merge minor

2020-05-12 17:04 UTC, merged