[12.0][IMP] partner_contact_address_default: allow selecting all partner re…
OCA/partner-contact pull request #948
Opened 2020-08-16 16:05 UTC by skeller1

…cords as default

2021-10-29 16:55 UTC, NL66278 approved these changes
:+1: LGTM

2021-12-04 18:16 UTC, dreispt commented
/ocabot merge minor

2022-02-17 19:45 UTC, dreispt commented
/ocabot merge nobump

2022-02-17 19:57 UTC, pedrobaeza requested changes

2022-02-17 19:57 UTC, pedrobaeza commented on partner_contact_address_default/models/res_config_settings.py
> +        default=True,
This should be False by default for not changing current behavior.

2022-02-22 07:15 UTC, pedrobaeza approved these changes

2022-02-22 07:15 UTC, pedrobaeza commented
/ocabot merge minor

2022-02-22 08:26 UTC, merged